-- =============================================================================
-- FIVE METAL MASONRY (FMM) - STATIC REFERENCE DATA SEED SCRIPT (DML)
-- Database Engine: DuckDB / ANSI SQL Compatible
-- Contains Master Canonical Seed Data for Series, Studies, Taxonomies, Aliases,
-- Dictionary Glossary, Document Catalog, Temple Places & Photographic Plates
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Table: series [T_ODS_SERIES (Archival Monograph Series)] (19 rows)
-- -----------------------------------------------------------------------------
INSERT INTO series (id, slug, name, scope, status, cover_image_url, sort_order, created_at, updated_at, created_by, updated_by) VALUES (1, 'panchaloha-primer', 'Panchaloha Primer', 'An introduction to the Panchaloha bronze art form.', 'completed', NULL, 1, '2026-09-13 12:01:18.737308', '2026-09-13 12:01:18.752354', 'curator', 'curator');
INSERT INTO series (id, slug, name, scope, status, cover_image_url, sort_order, created_at, updated_at, created_by, updated_by) VALUES (2, 'dictionary-of-iconography', 'Dictionary of Iconography', 'Glossary of terms related to iconography.', 'completed', NULL, 2, '2026-09-13 12:01:18.737308', '2026-09-13 12:01:18.752354', 'curator', 'curator');
INSERT INTO series (id, slug, name, scope, status, cover_image_url, sort_order, created_at, updated_at, created_by, updated_by) VALUES (3, 'tala', 'Tala', 'Series on iconometry and proportional systems.', 'completed', NULL, 3, '2026-09-13 12:01:18.737308', '2026-09-13 12:01:18.752354', 'curator', 'curator');
INSERT INTO series (id, slug, name, scope, status, cover_image_url, sort_order, created_at, updated_at, created_by, updated_by) VALUES (4, 'bronzecast', 'BronzeCast', 'Studies and notes on bronze and the bronze tradition.', 'completed', NULL, 4, '2026-09-13 12:01:18.737308', '2026-09-13 12:01:18.752354', 'curator', 'curator');
INSERT INTO series (id, slug, name, scope, status, cover_image_url, sort_order, created_at, updated_at, created_by, updated_by) VALUES (5, 'mythics', 'Mythics', 'Iconography of mythical characters.', 'completed', NULL, 5, '2026-09-13 12:01:18.737308', '2026-09-13 12:01:18.752354', 'curator', 'curator');
INSERT INTO series (id, slug, name, scope, status, cover_image_url, sort_order, created_at, updated_at, created_by, updated_by) VALUES (6, '108-tandava', '108 Tandava', 'Iconography of the 108 dance poses of Siva.', 'completed', NULL, 6, '2026-09-13 12:01:18.737308', '2026-09-13 12:01:18.752354', 'curator', 'curator');
INSERT INTO series (id, slug, name, scope, status, cover_image_url, sort_order, created_at, updated_at, created_by, updated_by) VALUES (7, 'ayudha', 'Ayudha', 'Visual study of weapons and attributes held by divinities.', 'completed', NULL, 7, '2026-09-13 12:01:18.737308', '2026-09-13 12:01:18.752354', 'curator', 'curator');
INSERT INTO series (id, slug, name, scope, status, cover_image_url, sort_order, created_at, updated_at, created_by, updated_by) VALUES (8, 'roopam', 'Roopam', 'Iconography of minor and lesser-known divine forms.', 'ongoing', NULL, 8, '2026-09-13 12:01:18.737308', '2026-09-13 12:01:18.752354', 'curator', 'curator');
INSERT INTO series (id, slug, name, scope, status, cover_image_url, sort_order, created_at, updated_at, created_by, updated_by) VALUES (9, 'god-is-in-the-details', 'God is in the Details', 'Detailed visual iconographic study of museum and temple bronzes.', 'ongoing', NULL, 9, '2026-09-13 12:01:18.737308', '2026-09-13 12:01:18.752354', 'curator', 'curator');
INSERT INTO series (id, slug, name, scope, status, cover_image_url, sort_order, created_at, updated_at, created_by, updated_by) VALUES (10, '5mm-iconography-quiz', '5MM Iconography Quiz', 'Quiz-based engagement and learning around iconography.', 'ongoing', NULL, 10, '2026-09-13 12:01:18.737308', '2026-09-13 12:01:18.752354', 'curator', 'curator');
INSERT INTO series (id, slug, name, scope, status, cover_image_url, sort_order, created_at, updated_at, created_by, updated_by) VALUES (11, 'majors-iconography', 'Majors Iconography', 'Detailed thematic studies of major divinities; approximately 70 studies to date.', 'ongoing', NULL, 11, '2026-09-13 12:01:18.737308', '2026-09-13 12:01:18.752354', 'curator', 'curator');
INSERT INTO series (id, slug, name, scope, status, cover_image_url, sort_order, created_at, updated_at, created_by, updated_by) VALUES (12, 'mudra', 'Mudra', 'Visual study of hand gestures, mudras and hastas.', 'ongoing', NULL, 12, '2026-09-13 12:01:18.737308', '2026-09-13 12:01:18.752354', 'curator', 'curator');
INSERT INTO series (id, slug, name, scope, status, cover_image_url, sort_order, created_at, updated_at, created_by, updated_by) VALUES (13, '108-divya-desams', '108 Divya Desams', 'Iconography of Vishnu across the 108 Vaishnava shrines.', 'ongoing', NULL, 13, '2026-09-13 12:01:18.737308', '2026-09-13 12:01:18.752354', 'curator', 'curator');
INSERT INTO series (id, slug, name, scope, status, cover_image_url, sort_order, created_at, updated_at, created_by, updated_by) VALUES (14, 'abharana', 'Abharana', 'Visual study of ornamentation and attire.', 'ongoing', NULL, 14, '2026-09-13 12:01:18.737308', '2026-09-13 12:01:18.752354', 'curator', 'curator');
INSERT INTO series (id, slug, name, scope, status, cover_image_url, sort_order, created_at, updated_at, created_by, updated_by) VALUES (15, 'temple-iconography', 'Temple Iconography', 'Visual study of temple architecture and sculptures.', 'ongoing', NULL, 15, '2026-09-13 12:01:18.737308', '2026-09-13 12:01:18.752354', 'curator', 'curator');
INSERT INTO series (id, slug, name, scope, status, cover_image_url, sort_order, created_at, updated_at, created_by, updated_by) VALUES (16, 'iconography-shelf', 'Iconography Shelf', 'A guided view of books on iconography.', 'ongoing', NULL, 16, '2026-09-13 12:01:18.737308', '2026-09-13 12:01:18.752354', 'curator', 'curator');
INSERT INTO series (id, slug, name, scope, status, cover_image_url, sort_order, created_at, updated_at, created_by, updated_by) VALUES (17, 'padimam', 'Padimam', 'Visual study of stone sculptures in temples.', 'upcoming', NULL, 17, '2026-09-13 12:01:18.737308', '2026-09-13 12:01:18.752354', 'curator', 'curator');
INSERT INTO series (id, slug, name, scope, status, cover_image_url, sort_order, created_at, updated_at, created_by, updated_by) VALUES (18, 'vahana', 'Vahana', 'Visual study of the mounts of divinities.', 'upcoming', NULL, 18, '2026-09-13 12:01:18.737308', '2026-09-13 12:01:18.752354', 'curator', 'curator');
INSERT INTO series (id, slug, name, scope, status, cover_image_url, sort_order, created_at, updated_at, created_by, updated_by) VALUES (19, 'asana', 'Asana', 'Study of postures.', 'upcoming', NULL, 19, '2026-09-13 12:01:18.737308', '2026-09-13 12:01:18.752354', 'curator', 'curator');

-- -----------------------------------------------------------------------------
-- Table: studies [T_ODS_STUDIES (Curated Research Monographs)] (7 rows)
-- -----------------------------------------------------------------------------
INSERT INTO studies (id, slug, title, subtitle, study_number, series_id, content_type, access_level, status, summary_markdown, original_publication_date, cover_image_url, total_slides, search_keywords, curator_notes, created_at, updated_at, created_by, updated_by) VALUES ('s_ganesa_001', 'ganesa-variations-in-iconography', 'Ganesa: Variations in Iconography', 'Postural/Compositional, Anatomical, and Regional Distinctive Forms', 'Study 001', 11, 'study', 'public', 'published', 'This handcrafted Panchaloha bronze Ganesha is depicted seated in   lalitasana   on a tiered lotus pedestal. The four-armed form holds   ankusa   and   pasa   in the upper hands, and   danta   and   modaka   in the lower hands. The trunk curves across the body, with broad ears, rounded abdomen and de', '2026-09-11', '/storage/images/ganesa-variations-in-iconography/slide_1.png', 7, 'Objects, Symbols, Asina, Lalitasana, Ganesha, Panchaloha, Modaka, Ankusa', 'Curated from Five Metal Masonry authentic bronze collection', '2026-09-13 12:01:18.771914', '2026-09-13 12:01:18.796506', 'curator', 'curator');
INSERT INTO studies (id, slug, title, subtitle, study_number, series_id, content_type, access_level, status, summary_markdown, original_publication_date, cover_image_url, total_slides, search_keywords, curator_notes, created_at, updated_at, created_by, updated_by) VALUES ('s_nataraja_002', 'nataraja-cosmic-dance-iconometry', 'Nataraja: Cosmic Dance & Classical Iconometry', 'Iconography of the Ananda Tandava and Chola Bronzes', 'Study 002', 11, 'study', 'member_only', 'published', 'Handcrafted panchaloha bronze icon of Naṭarāja from the Masterpieces collection, depicted in the classic ānanda-tāṇḍava within a prabhāmaṇḍala of flaming tongues. The four-armed form presents the ḍamaru and agni in the upper hands, with abhaya and gaja-hasta (karaṇa) articulating the lower gestures.', '2026-09-12', '/storage/images/nataraja-cosmic-dance-iconometry/slide_1.png', 4, 'Nataraja, Shiva, Tandava, Ananda Tandava, Apasmara, Chola, Bronze, Agni, Damaru', 'Premium Monograph reserved for Scholar Pro Members', '2026-09-13 12:01:18.771914', '2026-09-13 12:01:18.796506', 'curator', 'curator');
INSERT INTO studies (id, slug, title, subtitle, study_number, series_id, content_type, access_level, status, summary_markdown, original_publication_date, cover_image_url, total_slides, search_keywords, curator_notes, created_at, updated_at, created_by, updated_by) VALUES ('s_uchchhishta_003', 'uchchhishta-ganapati-tantric-iconography', 'Uchchhishta Ganapati: Tantric Dual-Figure Composition', 'Esoteric Ganapatya Iconography and Devi Manifestation', 'Study 003', 11, 'study', 'public', 'published', 'Handcrafted panchaloha bronze icon of Uchchhishta Ganapati, a tantric form of Ganesha, depicted seated with the Devi on his left lap. The composition presents an intimate dual-figure arrangement, with the four-armed form carrying canonical attributes, and the trunk extending across towards the Devi.', '2026-09-12', '/storage/images/uchchhishta-ganapati-tantric-iconography/slide_1.png', 4, 'Symbols, Tantric, Ganapatya, Devi, Panchaloha, Dual Figure, Lalitasana', 'Public Access', '2026-09-13 12:01:18.771914', '2026-09-13 12:01:18.796506', 'curator', 'curator');
INSERT INTO studies (id, slug, title, subtitle, study_number, series_id, content_type, access_level, status, summary_markdown, original_publication_date, cover_image_url, total_slides, search_keywords, curator_notes, created_at, updated_at, created_by, updated_by) VALUES ('s_kaliya_004', 'kaliya-tandava-krishna-iconometry', 'Kaliya Tandava Krishna: Dynamic Postural Iconometry', 'Serpentine Foot Placement and Equilibrium in Chola-Style Bronzes', 'Study 004', 6, 'study', 'public', 'published', 'Handcrafted Panchaloha bronze of Kaliya Tandava Krishna  , from our Masterpieces Collection  
  Krishna is depicted dancing upon the subdued serpent Kaliya, balancing on his raised multi-hooded head with one leg firmly placed and the other lifted in a dynamic dancing posture. His right hand is raise', '2026-09-12', '/storage/images/kaliya-tandava-krishna-iconometry/slide_1.png', 4, 'History, Nrtta, Tandava, Krishna, Serpent, Bronze Cast, Chola', 'Public Access', '2026-09-13 12:01:18.771914', '2026-09-13 12:01:18.796506', 'curator', 'curator');
INSERT INTO studies (id, slug, title, subtitle, study_number, series_id, content_type, access_level, status, summary_markdown, original_publication_date, cover_image_url, total_slides, search_keywords, curator_notes, created_at, updated_at, created_by, updated_by) VALUES ('s_venugopala_005', 'krishna-venugopala-tribhanga-posture', 'Krishna Venugopala: The Tribhanga Posture & Bamboo Flute', 'Three-Bend Canon, Cowherd Attire, and Cadence of the Flute', 'Study 005', 3, 'study', 'member_only', 'published', 'Venugopala, the flute-playing form of Krishna, is depicted standing in   svastikasana  , with one leg gracefully crossed before the other. His hands are raised towards his lips, holding the   venu (flute)   in his characteristic flute-playing gesture.  
  His hair is arranged in an elaborate   kesa-', '2026-09-12', '/storage/images/krishna-venugopala-tribhanga-posture/slide_1.png', 4, 'Material Culture, Tribhanga, Tala, Venugopala, Venu, Timeless Collection', 'Scholar Pro Member', '2026-09-13 12:01:18.771914', '2026-09-13 12:01:18.796506', 'curator', 'curator');
INSERT INTO studies (id, slug, title, subtitle, study_number, series_id, content_type, access_level, status, summary_markdown, original_publication_date, cover_image_url, total_slides, search_keywords, curator_notes, created_at, updated_at, created_by, updated_by) VALUES ('s_radhakrishna_006', 'radha-krishna-composite-proportions', 'Radha-Krishna: Composite Divine Proportions', 'Dual-Scale Harmony and Shilpa Shastra Dvandva Rules', 'Study 006', 3, 'study', 'member_only', 'published', 'A handcrafted Panchaloha bronze depiction of   Radha and Krishna  , composed as a paired standing form rooted in the South Indian sculptural tradition.  
  Krishna is shown as   Venugopala  , playing the flute held across his body, his legs arranged in a crossed   svastikāsana   stance. He wears an ', '2026-09-12', '/storage/images/radha-krishna-composite-proportions/slide_1.png', 4, 'Architecture, Dvandva, Radha, Krishna, Bronze, Masterpiece', 'Scholar Pro Member', '2026-09-13 12:01:18.771914', '2026-09-13 12:01:18.796506', 'curator', 'curator');
INSERT INTO studies (id, slug, title, subtitle, study_number, series_id, content_type, access_level, status, summary_markdown, original_publication_date, cover_image_url, total_slides, search_keywords, curator_notes, created_at, updated_at, created_by, updated_by) VALUES ('s_study_of_rare_va_6d2f', 'study-of-rare-varahi-iconography', 'Study of Rare Varahi Iconography', NULL, NULL, 1, 'study', 'public', 'draft', NULL, NULL, NULL, 0, NULL, NULL, '2026-09-13 06:38:20.246255', '2026-09-13 06:38:20.246255', 'ananth.seetharaman@gmail.com', 'ananth.seetharaman@gmail.com');

-- -----------------------------------------------------------------------------
-- Table: study_slides [T_RAW_STUDY_SLIDES (High-Res Photographic Plates & Slides)] (27 rows)
-- -----------------------------------------------------------------------------
INSERT INTO study_slides (id, study_id, slide_number, slide_title, image_url, thumbnail_url, caption, extracted_ocr_text, cleaned_text, visual_elements_summary, sort_order) VALUES ('sl_1', 's_ganesa_001', 1, 'Variations in Iconography: Scope & Methodology', '/storage/images/ganesa-variations-in-iconography/slide_1.png', '/storage/images/ganesa-variations-in-iconography/slide_1.png', 'Introductory scope outlining visible variations in posture, composition, arms, faces, trunk orientation, and regional configurations.', 'ICONOGRAPHY VARIATIONS IN ICONOGRAPHY The iconography of Ganesa presents considerable variation in posture, composition and anatomical form. This study examines these visible variations— including the number of arms and faces, disposition of the trunk and distinctive regional configurations—rather than presenting another prescribed set of forms. Some of these variations occur within the well- known 32 forms of GaQeSa (covered earlier) and are revisited here specifically to -illustrate their distinctive iconographic features. This study considers variations that are visibly rather than expressed in the icon itself, distinctions based solely on epithets, legends or sthala-puräQa traditions. FIVE METAL MASONRY fivemetalmasonry.com', 'The iconography of Gaṇeśa presents considerable variation in posture, composition and anatomical form. This study examines these visible variations—including the number of arms and faces, disposition of the trunk and distinctive regional configurations—rather than presenting another prescribed set of forms. Some of these variations occur within the well-known 32 forms of Gaṇeśa (covered earlier) and are revisited here specifically to illustrate their distinctive iconographic features. This study considers variations that are visibly expressed in the icon itself, rather than distinctions based solely on epithets, legends or sthala-purāṇa traditions.', 'Title parchment with Five Metal Masonry hand emblem logo.', 1);
INSERT INTO study_slides (id, study_id, slide_number, slide_title, image_url, thumbnail_url, caption, extracted_ocr_text, cleaned_text, visual_elements_summary, sort_order) VALUES ('sl_2', 's_ganesa_001', 2, 'Taxonomy of Ganesa Variations: Postural, Anatomical, Regional', '/storage/images/ganesa-variations-in-iconography/slide_2.png', '/storage/images/ganesa-variations-in-iconography/slide_2.png', 'Complete systematic breakdown: Postural & Compositional, Anatomical (Bahu-bheda, Mukha-bheda, Sunda-bheda), Regional forms, and Vahana variations.', 'ICONOGRAPHY QAN ESA VARIATIONS IN ICONOGRAPHY 1. POSTURAL & COMPOSITIONAL VARIATIONS • ÄsTna — seated; several variations in leg disposition occur. • Sthänaka — standing • Nrtta — dancing • Mü$kavähana — mounted/seated upon the mü#ika • With Devi/Devis • Samkara Murtis - ganesa combined with another divinity 2. ANATOMICAL VARIATIONS Bähu-bheda — number of arms • Dvibhuja — two-armed representations • Caturbhuja — four-armed; the most familiar depiction. • Sadbhuja, A#Cabhuja, Dagabhuja and other multi-armed forms Mukha-bheda — number of heads/faces • Ekamukha single-headed, the usual form. • Dvimukha / Trimukha / Paficamukha — clearly established forms Sundä-bheda — orientation of the trunk • Left-turning • Right-turning • Central/descending 3. REGIONAL / DISTINCTIVE FORMS FIVE METAL MASONRY fivemetalmasonry.com • Ädi Vinäyaka, Thilatharpanapuri — human-headed form • TriSuQ4a GaQapati, Pune— three-trunked form • Garh Ganesh, Jaipur - trunkless form VAHANA VARIATION Distinctive vähanas are covered under their respective forms — Heramba Ganapati, the paöcamukha form, with the lion; and TriSutpda Ganapati, with the peacock.', '1. Postural & Compositional Variations: Āsīna (seated), Sthānaka (standing), Nṛtta (dancing), Mūṣikavāhana (mounted upon mūṣika), With Devi/Devis, Saṅkara Mūrtis (combined with another divinity). 2. Anatomical Variations: Bāhu-bheda (arms: Dvibhuja, Caturbhuja, Ṣaḍbhuja, Aṣṭabhuja, Daśabhuja), Mukha-bheda (heads: Ekamukha, Dvimukha, Trimukha, Pañcamukha), Śuṇḍā-bheda (trunk: Left-turning, Right-turning, Central/descending). 3. Regional / Distinctive Forms: Ādi Vināyaka, Thilatharpanapuri (human-headed), Triśuṇḍa Gaṇapati, Pune (three-trunked), Garh Ganesh, Jaipur (trunkless). Vāhana Variation: Heramba Gaṇapati with lion (siṃha); Triśuṇḍa Gaṇapati with peacock (mayūra).', 'Comprehensive classification list on aged parchment background.', 2);
INSERT INTO study_slides (id, study_id, slide_number, slide_title, image_url, thumbnail_url, caption, extracted_ocr_text, cleaned_text, visual_elements_summary, sort_order) VALUES ('sl_3', 's_ganesa_001', 3, 'Comparative Plate: 20 Iconographic Variations of Ganesa', '/storage/images/ganesa-variations-in-iconography/slide_3.png', '/storage/images/ganesa-variations-in-iconography/slide_3.png', 'Illustrated comparative plate demonstrating the 20 visual variations drawn from bronzes, stone sculptures, and classical iconometry.', 'ICONOGRAPHY VARIATIONS IN ICONOGRAPHY POSTURAL/COMPOSITIONAL • ANATOMICAL • REGIONAL POSTURAL & COMPOSITIONAL VARIATIONS ASINA SAD-BHUJA STANA ASTA-BHUJA MUSHIKA VAHANA ANATOMICAL VARIATIONS ASA-BHUJA SODASA-BÅUJA REGIONAL DISTINCTIVE FORMS DEVI SAHITA AMKARA MURTI ATUR-BHUJ DAKSINAVARTL•: FIVE METAL MASONRY fivemetalmasonry.com ADI- TN TRISHUND PANA''fi, PUNE GARH GANAPTI, JAIPUR', 'Visual comparative iconography plate illustrating: Row 1 (Postural): Āsīna, Sthānaka, Nṛtta, Mūṣika Vāhana, Devi Sahita, Saṅkara Mūrtis. Row 2 & 3 (Anatomical): Dvi-mukha, Tri-mukha, Pañca-mukha, Dvi-bhuja, Catur-bhuja, Ṣaḍ-bhuja, Aṣṭa-bhuja, Daśa-bhuja, Ṣoḍaśa-bhuja, Vāmāvarta, Dakṣiṇāvarta. Row 4 (Regional): Ādi-Vināyaka (Tamil Nadu, Human Form), Trishund Ganapati (Pune, Three Trunked), Garh Ganapati (Jaipur, Trunkless).', '20 detailed hand-drawn iconographic line drawings in 4 registers.', 3);
INSERT INTO study_slides (id, study_id, slide_number, slide_title, image_url, thumbnail_url, caption, extracted_ocr_text, cleaned_text, visual_elements_summary, sort_order) VALUES ('sl_4', 's_ganesa_001', 4, 'Postural Variations: Asina | Sitting Postures in Detail', '/storage/images/ganesa-variations-in-iconography/slide_4.png', '/storage/images/ganesa-variations-in-iconography/slide_4.png', 'Deep iconographic reading of seated forms: padmasana, sukhasana, lalitasana, ardhaparyankasana, and bhadrasana.', 'ICONOGRAPHY POSTURAL VARIATIONS ÄSiNA I SITTING In the äsrna form, Ganesa is represented seated in a stable and composed posturer with the legs arranged in several ways according to the specific iconographic form. He in padmäsana (lotus may sit posture), sukhäsana (easy posture), lalitäsana (posture of royal ease), or ardhaparyahkäsana (with one leg — pendant and the other drawn up). He may also be shown in bhadräsana (a formal seated posture, generally with both feet placed on a support or with the legs arranged symmetrically). The characteristic elephant head, large ears and prominent rounded belly are retained, while the number ¯ of arms, gestures and attributes may vary according to the specific iconographic form. FIVE METAL MASONRY fivemetalmasonry.com', 'In the āsīna form, Gaṇeśa is represented seated in a stable and composed posture, with the legs arranged in several ways according to the specific iconographic form. He may sit in padmāsana (lotus posture), sukhāsana (easy posture), lalitāsana (posture of royal ease), or ardhaparyaṅkāsana (with one leg pendant and the other drawn up). He may also be shown in bhadrāsana (a formal seated posture, generally with both feet placed on a support or with the legs arranged symmetrically). The characteristic elephant head, large ears and prominent rounded belly are retained, while the number of arms, gestures and attributes may vary according to the specific iconographic form.', 'Line drawing of Caturbhuja Ganesha seated in Lalitasana on a padmapitha holding pasa and ankusa with modaka on trunk.', 4);
INSERT INTO study_slides (id, study_id, slide_number, slide_title, image_url, thumbnail_url, caption, extracted_ocr_text, cleaned_text, visual_elements_summary, sort_order) VALUES ('sl_nat_1', 's_nataraja_002', 1, 'Plate 1: Canonical Perspective - Nataraja 18" Masterpiece', '/storage/images/nataraja-cosmic-dance-iconometry/slide_1.png', '/storage/images/nataraja-cosmic-dance-iconometry/slide_1.png', 'Handcrafted panchaloha bronze icon of Naṭarāja from the Masterpieces collection, depicted in the classic ānanda-tāṇḍava within a prabhāmaṇḍala of flaming tongues. The four-armed form presents the ḍamaru and agni in the upper hands, with abhaya and gaja-hasta (karaṇa) articulating the lower gestures.', 'Handcrafted panchaloha bronze icon of Naṭarāja from the Masterpieces collection, depicted in the classic ānanda-tāṇḍava within a prabhāmaṇḍala of flaming tongues. The four-armed form presents the ḍamaru and agni in the upper hands, with abhaya and gaja-hasta (karaṇa) articulating the lower gestures.', 'Handcrafted panchaloha bronze icon of Naṭarāja from the Masterpieces collection, depicted in the classic ānanda-tāṇḍava within a prabhāmaṇḍala of flaming tongues. The four-armed form presents the ḍamaru and agni in the upper hands, with abhaya and gaja-hasta (karaṇa) articulating the lower gestures.', 'Plate 1: Canonical Perspective - Nataraja 18" Masterpiece', 1);
INSERT INTO study_slides (id, study_id, slide_number, slide_title, image_url, thumbnail_url, caption, extracted_ocr_text, cleaned_text, visual_elements_summary, sort_order) VALUES ('sl_nat_2', 's_nataraja_002', 2, 'Plate 2: Canonical Perspective - Nataraja 18" Masterpiece', '/storage/images/nataraja-cosmic-dance-iconometry/slide_2.png', '/storage/images/nataraja-cosmic-dance-iconometry/slide_2.png', 'Handcrafted panchaloha bronze icon of Naṭarāja from the Masterpieces collection, depicted in the classic ānanda-tāṇḍava within a prabhāmaṇḍala of flaming tongues. The four-armed form presents the ḍamaru and agni in the upper hands, with abhaya and gaja-hasta (karaṇa) articulating the lower gestures.', 'Handcrafted panchaloha bronze icon of Naṭarāja from the Masterpieces collection, depicted in the classic ānanda-tāṇḍava within a prabhāmaṇḍala of flaming tongues. The four-armed form presents the ḍamaru and agni in the upper hands, with abhaya and gaja-hasta (karaṇa) articulating the lower gestures.', 'Handcrafted panchaloha bronze icon of Naṭarāja from the Masterpieces collection, depicted in the classic ānanda-tāṇḍava within a prabhāmaṇḍala of flaming tongues. The four-armed form presents the ḍamaru and agni in the upper hands, with abhaya and gaja-hasta (karaṇa) articulating the lower gestures.', 'Plate 2: Canonical Perspective - Nataraja 18" Masterpiece', 2);
INSERT INTO study_slides (id, study_id, slide_number, slide_title, image_url, thumbnail_url, caption, extracted_ocr_text, cleaned_text, visual_elements_summary, sort_order) VALUES ('sl_nat_3', 's_nataraja_002', 3, 'Plate 3: Canonical Perspective - Nataraja 18" Masterpiece', '/storage/images/nataraja-cosmic-dance-iconometry/slide_3.png', '/storage/images/nataraja-cosmic-dance-iconometry/slide_3.png', 'Handcrafted panchaloha bronze icon of Naṭarāja from the Masterpieces collection, depicted in the classic ānanda-tāṇḍava within a prabhāmaṇḍala of flaming tongues. The four-armed form presents the ḍamaru and agni in the upper hands, with abhaya and gaja-hasta (karaṇa) articulating the lower gestures.', 'Handcrafted panchaloha bronze icon of Naṭarāja from the Masterpieces collection, depicted in the classic ānanda-tāṇḍava within a prabhāmaṇḍala of flaming tongues. The four-armed form presents the ḍamaru and agni in the upper hands, with abhaya and gaja-hasta (karaṇa) articulating the lower gestures.', 'Handcrafted panchaloha bronze icon of Naṭarāja from the Masterpieces collection, depicted in the classic ānanda-tāṇḍava within a prabhāmaṇḍala of flaming tongues. The four-armed form presents the ḍamaru and agni in the upper hands, with abhaya and gaja-hasta (karaṇa) articulating the lower gestures.', 'Plate 3: Canonical Perspective - Nataraja 18" Masterpiece', 3);
INSERT INTO study_slides (id, study_id, slide_number, slide_title, image_url, thumbnail_url, caption, extracted_ocr_text, cleaned_text, visual_elements_summary, sort_order) VALUES ('sl_nat_4', 's_nataraja_002', 4, 'Plate 4: Canonical Perspective - Nataraja 18" Masterpiece', '/storage/images/nataraja-cosmic-dance-iconometry/slide_4.png', '/storage/images/nataraja-cosmic-dance-iconometry/slide_4.png', 'Handcrafted panchaloha bronze icon of Naṭarāja from the Masterpieces collection, depicted in the classic ānanda-tāṇḍava within a prabhāmaṇḍala of flaming tongues. The four-armed form presents the ḍamaru and agni in the upper hands, with abhaya and gaja-hasta (karaṇa) articulating the lower gestures.', 'Handcrafted panchaloha bronze icon of Naṭarāja from the Masterpieces collection, depicted in the classic ānanda-tāṇḍava within a prabhāmaṇḍala of flaming tongues. The four-armed form presents the ḍamaru and agni in the upper hands, with abhaya and gaja-hasta (karaṇa) articulating the lower gestures.', 'Handcrafted panchaloha bronze icon of Naṭarāja from the Masterpieces collection, depicted in the classic ānanda-tāṇḍava within a prabhāmaṇḍala of flaming tongues. The four-armed form presents the ḍamaru and agni in the upper hands, with abhaya and gaja-hasta (karaṇa) articulating the lower gestures.', 'Plate 4: Canonical Perspective - Nataraja 18" Masterpiece', 4);
INSERT INTO study_slides (id, study_id, slide_number, slide_title, image_url, thumbnail_url, caption, extracted_ocr_text, cleaned_text, visual_elements_summary, sort_order) VALUES ('sl_s_uchchhishta_003_1', 's_uchchhishta_003', 1, 'Plate 1: Canonical Perspective', '/storage/images/uchchhishta-ganapati-tantric-iconography/slide_1.png', '/storage/images/uchchhishta-ganapati-tantric-iconography/slide_1.png', 'Handcrafted panchaloha bronze icon of Uchchhishta Ganapati, a tantric form of Ganesha, depicted seated with the Devi on his left lap. The composition presents an intimate dual-figure arrangement, with the four-armed form carrying canonical attributes, and the trunk extending across towards the Devi.', 'Handcrafted panchaloha bronze icon of Uchchhishta Ganapati, a tantric form of Ganesha, depicted seated with the Devi on his left lap. The composition presents an intimate dual-figure arrangement, with the four-armed form carrying canonical attributes, and the trunk extending across towards the Devi.', 'Handcrafted panchaloha bronze icon of Uchchhishta Ganapati, a tantric form of Ganesha, depicted seated with the Devi on his left lap. The composition presents an intimate dual-figure arrangement, with the four-armed form carrying canonical attributes, and the trunk extending across towards the Devi.', 'Plate 1: Canonical Perspective', 1);
INSERT INTO study_slides (id, study_id, slide_number, slide_title, image_url, thumbnail_url, caption, extracted_ocr_text, cleaned_text, visual_elements_summary, sort_order) VALUES ('sl_s_uchchhishta_003_2', 's_uchchhishta_003', 2, 'Plate 2: Canonical Perspective', '/storage/images/uchchhishta-ganapati-tantric-iconography/slide_2.png', '/storage/images/uchchhishta-ganapati-tantric-iconography/slide_2.png', 'Handcrafted panchaloha bronze icon of Uchchhishta Ganapati, a tantric form of Ganesha, depicted seated with the Devi on his left lap. The composition presents an intimate dual-figure arrangement, with the four-armed form carrying canonical attributes, and the trunk extending across towards the Devi.', 'Handcrafted panchaloha bronze icon of Uchchhishta Ganapati, a tantric form of Ganesha, depicted seated with the Devi on his left lap. The composition presents an intimate dual-figure arrangement, with the four-armed form carrying canonical attributes, and the trunk extending across towards the Devi.', 'Handcrafted panchaloha bronze icon of Uchchhishta Ganapati, a tantric form of Ganesha, depicted seated with the Devi on his left lap. The composition presents an intimate dual-figure arrangement, with the four-armed form carrying canonical attributes, and the trunk extending across towards the Devi.', 'Plate 2: Canonical Perspective', 2);
INSERT INTO study_slides (id, study_id, slide_number, slide_title, image_url, thumbnail_url, caption, extracted_ocr_text, cleaned_text, visual_elements_summary, sort_order) VALUES ('sl_s_uchchhishta_003_3', 's_uchchhishta_003', 3, 'Plate 3: Canonical Perspective', '/storage/images/uchchhishta-ganapati-tantric-iconography/slide_3.png', '/storage/images/uchchhishta-ganapati-tantric-iconography/slide_3.png', 'Handcrafted panchaloha bronze icon of Uchchhishta Ganapati, a tantric form of Ganesha, depicted seated with the Devi on his left lap. The composition presents an intimate dual-figure arrangement, with the four-armed form carrying canonical attributes, and the trunk extending across towards the Devi.', 'Handcrafted panchaloha bronze icon of Uchchhishta Ganapati, a tantric form of Ganesha, depicted seated with the Devi on his left lap. The composition presents an intimate dual-figure arrangement, with the four-armed form carrying canonical attributes, and the trunk extending across towards the Devi.', 'Handcrafted panchaloha bronze icon of Uchchhishta Ganapati, a tantric form of Ganesha, depicted seated with the Devi on his left lap. The composition presents an intimate dual-figure arrangement, with the four-armed form carrying canonical attributes, and the trunk extending across towards the Devi.', 'Plate 3: Canonical Perspective', 3);
INSERT INTO study_slides (id, study_id, slide_number, slide_title, image_url, thumbnail_url, caption, extracted_ocr_text, cleaned_text, visual_elements_summary, sort_order) VALUES ('sl_s_uchchhishta_003_4', 's_uchchhishta_003', 4, 'Plate 4: Canonical Perspective', '/storage/images/uchchhishta-ganapati-tantric-iconography/slide_4.png', '/storage/images/uchchhishta-ganapati-tantric-iconography/slide_4.png', 'Handcrafted panchaloha bronze icon of Uchchhishta Ganapati, a tantric form of Ganesha, depicted seated with the Devi on his left lap. The composition presents an intimate dual-figure arrangement, with the four-armed form carrying canonical attributes, and the trunk extending across towards the Devi.', 'Handcrafted panchaloha bronze icon of Uchchhishta Ganapati, a tantric form of Ganesha, depicted seated with the Devi on his left lap. The composition presents an intimate dual-figure arrangement, with the four-armed form carrying canonical attributes, and the trunk extending across towards the Devi.', 'Handcrafted panchaloha bronze icon of Uchchhishta Ganapati, a tantric form of Ganesha, depicted seated with the Devi on his left lap. The composition presents an intimate dual-figure arrangement, with the four-armed form carrying canonical attributes, and the trunk extending across towards the Devi.', 'Plate 4: Canonical Perspective', 4);
INSERT INTO study_slides (id, study_id, slide_number, slide_title, image_url, thumbnail_url, caption, extracted_ocr_text, cleaned_text, visual_elements_summary, sort_order) VALUES ('sl_s_kaliya_004_1', 's_kaliya_004', 1, 'Plate 1: Canonical Perspective', '/storage/images/kaliya-tandava-krishna-iconometry/slide_1.png', '/storage/images/kaliya-tandava-krishna-iconometry/slide_1.png', 'Handcrafted Panchaloha bronze of Kaliya Tandava Krishna  , from our Masterpieces Collection  
  Krishna is depicted dancing upon the subdued serpent Kaliya, balancing on his raised multi-hooded head with one leg firmly placed and the other lifted in a dynamic dancing posture. His right hand is raise', 'Handcrafted Panchaloha bronze of Kaliya Tandava Krishna  , from our Masterpieces Collection  
  Krishna is depicted dancing upon the subdued serpent Kaliya, balancing on his raised multi-hooded head with one leg firmly placed and the other lifted in a dynamic dancing posture. His right hand is raise', 'Handcrafted Panchaloha bronze of Kaliya Tandava Krishna  , from our Masterpieces Collection  
  Krishna is depicted dancing upon the subdued serpent Kaliya, balancing on his raised multi-hooded head with one leg firmly placed and the other lifted in a dynamic dancing posture. His right hand is raise', 'Plate 1: Canonical Perspective', 1);
INSERT INTO study_slides (id, study_id, slide_number, slide_title, image_url, thumbnail_url, caption, extracted_ocr_text, cleaned_text, visual_elements_summary, sort_order) VALUES ('sl_s_kaliya_004_2', 's_kaliya_004', 2, 'Plate 2: Canonical Perspective', '/storage/images/kaliya-tandava-krishna-iconometry/slide_2.png', '/storage/images/kaliya-tandava-krishna-iconometry/slide_2.png', 'Handcrafted Panchaloha bronze of Kaliya Tandava Krishna  , from our Masterpieces Collection  
  Krishna is depicted dancing upon the subdued serpent Kaliya, balancing on his raised multi-hooded head with one leg firmly placed and the other lifted in a dynamic dancing posture. His right hand is raise', 'Handcrafted Panchaloha bronze of Kaliya Tandava Krishna  , from our Masterpieces Collection  
  Krishna is depicted dancing upon the subdued serpent Kaliya, balancing on his raised multi-hooded head with one leg firmly placed and the other lifted in a dynamic dancing posture. His right hand is raise', 'Handcrafted Panchaloha bronze of Kaliya Tandava Krishna  , from our Masterpieces Collection  
  Krishna is depicted dancing upon the subdued serpent Kaliya, balancing on his raised multi-hooded head with one leg firmly placed and the other lifted in a dynamic dancing posture. His right hand is raise', 'Plate 2: Canonical Perspective', 2);
INSERT INTO study_slides (id, study_id, slide_number, slide_title, image_url, thumbnail_url, caption, extracted_ocr_text, cleaned_text, visual_elements_summary, sort_order) VALUES ('sl_s_kaliya_004_3', 's_kaliya_004', 3, 'Plate 3: Canonical Perspective', '/storage/images/kaliya-tandava-krishna-iconometry/slide_3.png', '/storage/images/kaliya-tandava-krishna-iconometry/slide_3.png', 'Handcrafted Panchaloha bronze of Kaliya Tandava Krishna  , from our Masterpieces Collection  
  Krishna is depicted dancing upon the subdued serpent Kaliya, balancing on his raised multi-hooded head with one leg firmly placed and the other lifted in a dynamic dancing posture. His right hand is raise', 'Handcrafted Panchaloha bronze of Kaliya Tandava Krishna  , from our Masterpieces Collection  
  Krishna is depicted dancing upon the subdued serpent Kaliya, balancing on his raised multi-hooded head with one leg firmly placed and the other lifted in a dynamic dancing posture. His right hand is raise', 'Handcrafted Panchaloha bronze of Kaliya Tandava Krishna  , from our Masterpieces Collection  
  Krishna is depicted dancing upon the subdued serpent Kaliya, balancing on his raised multi-hooded head with one leg firmly placed and the other lifted in a dynamic dancing posture. His right hand is raise', 'Plate 3: Canonical Perspective', 3);
INSERT INTO study_slides (id, study_id, slide_number, slide_title, image_url, thumbnail_url, caption, extracted_ocr_text, cleaned_text, visual_elements_summary, sort_order) VALUES ('sl_s_kaliya_004_4', 's_kaliya_004', 4, 'Plate 4: Canonical Perspective', '/storage/images/kaliya-tandava-krishna-iconometry/slide_4.png', '/storage/images/kaliya-tandava-krishna-iconometry/slide_4.png', 'Handcrafted Panchaloha bronze of Kaliya Tandava Krishna  , from our Masterpieces Collection  
  Krishna is depicted dancing upon the subdued serpent Kaliya, balancing on his raised multi-hooded head with one leg firmly placed and the other lifted in a dynamic dancing posture. His right hand is raise', 'Handcrafted Panchaloha bronze of Kaliya Tandava Krishna  , from our Masterpieces Collection  
  Krishna is depicted dancing upon the subdued serpent Kaliya, balancing on his raised multi-hooded head with one leg firmly placed and the other lifted in a dynamic dancing posture. His right hand is raise', 'Handcrafted Panchaloha bronze of Kaliya Tandava Krishna  , from our Masterpieces Collection  
  Krishna is depicted dancing upon the subdued serpent Kaliya, balancing on his raised multi-hooded head with one leg firmly placed and the other lifted in a dynamic dancing posture. His right hand is raise', 'Plate 4: Canonical Perspective', 4);
INSERT INTO study_slides (id, study_id, slide_number, slide_title, image_url, thumbnail_url, caption, extracted_ocr_text, cleaned_text, visual_elements_summary, sort_order) VALUES ('sl_s_venugopala_005_1', 's_venugopala_005', 1, 'Plate 1: Canonical Perspective', '/storage/images/krishna-venugopala-tribhanga-posture/slide_1.png', '/storage/images/krishna-venugopala-tribhanga-posture/slide_1.png', 'Venugopala, the flute-playing form of Krishna, is depicted standing in   svastikasana  , with one leg gracefully crossed before the other. His hands are raised towards his lips, holding the   venu (flute)   in his characteristic flute-playing gesture.  
  His hair is arranged in an elaborate   kesa-', 'Venugopala, the flute-playing form of Krishna, is depicted standing in   svastikasana  , with one leg gracefully crossed before the other. His hands are raised towards his lips, holding the   venu (flute)   in his characteristic flute-playing gesture.  
  His hair is arranged in an elaborate   kesa-', 'Venugopala, the flute-playing form of Krishna, is depicted standing in   svastikasana  , with one leg gracefully crossed before the other. His hands are raised towards his lips, holding the   venu (flute)   in his characteristic flute-playing gesture.  
  His hair is arranged in an elaborate   kesa-', 'Plate 1: Canonical Perspective', 1);
INSERT INTO study_slides (id, study_id, slide_number, slide_title, image_url, thumbnail_url, caption, extracted_ocr_text, cleaned_text, visual_elements_summary, sort_order) VALUES ('sl_s_venugopala_005_2', 's_venugopala_005', 2, 'Plate 2: Canonical Perspective', '/storage/images/krishna-venugopala-tribhanga-posture/slide_2.png', '/storage/images/krishna-venugopala-tribhanga-posture/slide_2.png', 'Venugopala, the flute-playing form of Krishna, is depicted standing in   svastikasana  , with one leg gracefully crossed before the other. His hands are raised towards his lips, holding the   venu (flute)   in his characteristic flute-playing gesture.  
  His hair is arranged in an elaborate   kesa-', 'Venugopala, the flute-playing form of Krishna, is depicted standing in   svastikasana  , with one leg gracefully crossed before the other. His hands are raised towards his lips, holding the   venu (flute)   in his characteristic flute-playing gesture.  
  His hair is arranged in an elaborate   kesa-', 'Venugopala, the flute-playing form of Krishna, is depicted standing in   svastikasana  , with one leg gracefully crossed before the other. His hands are raised towards his lips, holding the   venu (flute)   in his characteristic flute-playing gesture.  
  His hair is arranged in an elaborate   kesa-', 'Plate 2: Canonical Perspective', 2);
INSERT INTO study_slides (id, study_id, slide_number, slide_title, image_url, thumbnail_url, caption, extracted_ocr_text, cleaned_text, visual_elements_summary, sort_order) VALUES ('sl_s_venugopala_005_3', 's_venugopala_005', 3, 'Plate 3: Canonical Perspective', '/storage/images/krishna-venugopala-tribhanga-posture/slide_3.png', '/storage/images/krishna-venugopala-tribhanga-posture/slide_3.png', 'Venugopala, the flute-playing form of Krishna, is depicted standing in   svastikasana  , with one leg gracefully crossed before the other. His hands are raised towards his lips, holding the   venu (flute)   in his characteristic flute-playing gesture.  
  His hair is arranged in an elaborate   kesa-', 'Venugopala, the flute-playing form of Krishna, is depicted standing in   svastikasana  , with one leg gracefully crossed before the other. His hands are raised towards his lips, holding the   venu (flute)   in his characteristic flute-playing gesture.  
  His hair is arranged in an elaborate   kesa-', 'Venugopala, the flute-playing form of Krishna, is depicted standing in   svastikasana  , with one leg gracefully crossed before the other. His hands are raised towards his lips, holding the   venu (flute)   in his characteristic flute-playing gesture.  
  His hair is arranged in an elaborate   kesa-', 'Plate 3: Canonical Perspective', 3);
INSERT INTO study_slides (id, study_id, slide_number, slide_title, image_url, thumbnail_url, caption, extracted_ocr_text, cleaned_text, visual_elements_summary, sort_order) VALUES ('sl_s_venugopala_005_4', 's_venugopala_005', 4, 'Plate 4: Canonical Perspective', '/storage/images/krishna-venugopala-tribhanga-posture/slide_4.png', '/storage/images/krishna-venugopala-tribhanga-posture/slide_4.png', 'Venugopala, the flute-playing form of Krishna, is depicted standing in   svastikasana  , with one leg gracefully crossed before the other. His hands are raised towards his lips, holding the   venu (flute)   in his characteristic flute-playing gesture.  
  His hair is arranged in an elaborate   kesa-', 'Venugopala, the flute-playing form of Krishna, is depicted standing in   svastikasana  , with one leg gracefully crossed before the other. His hands are raised towards his lips, holding the   venu (flute)   in his characteristic flute-playing gesture.  
  His hair is arranged in an elaborate   kesa-', 'Venugopala, the flute-playing form of Krishna, is depicted standing in   svastikasana  , with one leg gracefully crossed before the other. His hands are raised towards his lips, holding the   venu (flute)   in his characteristic flute-playing gesture.  
  His hair is arranged in an elaborate   kesa-', 'Plate 4: Canonical Perspective', 4);
INSERT INTO study_slides (id, study_id, slide_number, slide_title, image_url, thumbnail_url, caption, extracted_ocr_text, cleaned_text, visual_elements_summary, sort_order) VALUES ('sl_s_radhakrishna_006_1', 's_radhakrishna_006', 1, 'Plate 1: Canonical Perspective', '/storage/images/radha-krishna-composite-proportions/slide_1.png', '/storage/images/radha-krishna-composite-proportions/slide_1.png', 'A handcrafted Panchaloha bronze depiction of   Radha and Krishna  , composed as a paired standing form rooted in the South Indian sculptural tradition.  
  Krishna is shown as   Venugopala  , playing the flute held across his body, his legs arranged in a crossed   svastikāsana   stance. He wears an ', 'A handcrafted Panchaloha bronze depiction of   Radha and Krishna  , composed as a paired standing form rooted in the South Indian sculptural tradition.  
  Krishna is shown as   Venugopala  , playing the flute held across his body, his legs arranged in a crossed   svastikāsana   stance. He wears an ', 'A handcrafted Panchaloha bronze depiction of   Radha and Krishna  , composed as a paired standing form rooted in the South Indian sculptural tradition.  
  Krishna is shown as   Venugopala  , playing the flute held across his body, his legs arranged in a crossed   svastikāsana   stance. He wears an ', 'Plate 1: Canonical Perspective', 1);
INSERT INTO study_slides (id, study_id, slide_number, slide_title, image_url, thumbnail_url, caption, extracted_ocr_text, cleaned_text, visual_elements_summary, sort_order) VALUES ('sl_s_radhakrishna_006_2', 's_radhakrishna_006', 2, 'Plate 2: Canonical Perspective', '/storage/images/radha-krishna-composite-proportions/slide_2.png', '/storage/images/radha-krishna-composite-proportions/slide_2.png', 'A handcrafted Panchaloha bronze depiction of   Radha and Krishna  , composed as a paired standing form rooted in the South Indian sculptural tradition.  
  Krishna is shown as   Venugopala  , playing the flute held across his body, his legs arranged in a crossed   svastikāsana   stance. He wears an ', 'A handcrafted Panchaloha bronze depiction of   Radha and Krishna  , composed as a paired standing form rooted in the South Indian sculptural tradition.  
  Krishna is shown as   Venugopala  , playing the flute held across his body, his legs arranged in a crossed   svastikāsana   stance. He wears an ', 'A handcrafted Panchaloha bronze depiction of   Radha and Krishna  , composed as a paired standing form rooted in the South Indian sculptural tradition.  
  Krishna is shown as   Venugopala  , playing the flute held across his body, his legs arranged in a crossed   svastikāsana   stance. He wears an ', 'Plate 2: Canonical Perspective', 2);
INSERT INTO study_slides (id, study_id, slide_number, slide_title, image_url, thumbnail_url, caption, extracted_ocr_text, cleaned_text, visual_elements_summary, sort_order) VALUES ('sl_s_radhakrishna_006_3', 's_radhakrishna_006', 3, 'Plate 3: Canonical Perspective', '/storage/images/radha-krishna-composite-proportions/slide_3.png', '/storage/images/radha-krishna-composite-proportions/slide_3.png', 'A handcrafted Panchaloha bronze depiction of   Radha and Krishna  , composed as a paired standing form rooted in the South Indian sculptural tradition.  
  Krishna is shown as   Venugopala  , playing the flute held across his body, his legs arranged in a crossed   svastikāsana   stance. He wears an ', 'A handcrafted Panchaloha bronze depiction of   Radha and Krishna  , composed as a paired standing form rooted in the South Indian sculptural tradition.  
  Krishna is shown as   Venugopala  , playing the flute held across his body, his legs arranged in a crossed   svastikāsana   stance. He wears an ', 'A handcrafted Panchaloha bronze depiction of   Radha and Krishna  , composed as a paired standing form rooted in the South Indian sculptural tradition.  
  Krishna is shown as   Venugopala  , playing the flute held across his body, his legs arranged in a crossed   svastikāsana   stance. He wears an ', 'Plate 3: Canonical Perspective', 3);
INSERT INTO study_slides (id, study_id, slide_number, slide_title, image_url, thumbnail_url, caption, extracted_ocr_text, cleaned_text, visual_elements_summary, sort_order) VALUES ('sl_s_radhakrishna_006_4', 's_radhakrishna_006', 4, 'Plate 4: Canonical Perspective', '/storage/images/radha-krishna-composite-proportions/slide_4.png', '/storage/images/radha-krishna-composite-proportions/slide_4.png', 'A handcrafted Panchaloha bronze depiction of   Radha and Krishna  , composed as a paired standing form rooted in the South Indian sculptural tradition.  
  Krishna is shown as   Venugopala  , playing the flute held across his body, his legs arranged in a crossed   svastikāsana   stance. He wears an ', 'A handcrafted Panchaloha bronze depiction of   Radha and Krishna  , composed as a paired standing form rooted in the South Indian sculptural tradition.  
  Krishna is shown as   Venugopala  , playing the flute held across his body, his legs arranged in a crossed   svastikāsana   stance. He wears an ', 'A handcrafted Panchaloha bronze depiction of   Radha and Krishna  , composed as a paired standing form rooted in the South Indian sculptural tradition.  
  Krishna is shown as   Venugopala  , playing the flute held across his body, his legs arranged in a crossed   svastikāsana   stance. He wears an ', 'Plate 4: Canonical Perspective', 4);
INSERT INTO study_slides (id, study_id, slide_number, slide_title, image_url, thumbnail_url, caption, extracted_ocr_text, cleaned_text, visual_elements_summary, sort_order) VALUES ('sl_8b18a50ad6b8', 's_ganesa_001', 5, 'Curated Slide: New Iconography Plate', '/storage/images/ganesa-variations-in-iconography/upload_d34ce8_WhatsApp Image 2026-09-11 at 7.29.36 AM.jpeg', '/storage/images/ganesa-variations-in-iconography/upload_d34ce8_WhatsApp Image 2026-09-11 at 7.29.36 AM.jpeg', 'Curated slide 5', 'ICONOGRAPHY POSTURAL VARIATIONS ÄSiNA I SITTING In the äsrna form, Ganesa is represented seated in a stable and composed posturer with the legs arranged in several ways according to the specific iconographic form. He in padmäsana (lotus may sit posture), sukhäsana (easy posture), lalitäsana (posture of royal ease), or ardhaparyahkäsana (with one leg — pendant and the other drawn up). He may also be shown in bhadräsana (a formal seated posture, generally with both feet placed on a support or with the legs arranged symmetrically). The characteristic elephant head, large ears and prominent rounded belly are retained, while the number ¯ of arms, gestures and attributes may vary according to the specific iconographic form. FIVE METAL MASONRY fivemetalmasonry.com', 'ICONOGRAPHY POSTURAL VARIATIONS ĀSĪNA I SITTING In the āsīna form, Ganesa is represented seated in a stable and composed posturer with the legs arranged in several ways according to the specific iconographic form. He in padmāsana (lotus may sit posture), sukhāsana (easy posture), lalitāsana (posture of royal ease), or ardhaparyaṅkāsana (with one leg — pendant and the other drawn up). He may also be shown in bhadrāsana (a formal seated posture, generally with both feet placed on a support or with the legs arranged symmetrically). The characteristic elephant head, large ears and prominent rounded belly are retained, while the number ¯ of arms, gestures and attributes may vary according to the specific iconographic form. FIVE METAL MASONRY fivemetalmasonry.com', 'High-resolution iconography plate', 5);
INSERT INTO study_slides (id, study_id, slide_number, slide_title, image_url, thumbnail_url, caption, extracted_ocr_text, cleaned_text, visual_elements_summary, sort_order) VALUES ('sl_cc51fdf0d4d3', 's_ganesa_001', 6, 'Shikhara Mudra: Canonical Iconographic Hand Gesture', '/storage/images/ganesa-variations-in-iconography/upload_c3b616_mudra.jfif', '/storage/images/ganesa-variations-in-iconography/upload_c3b616_mudra.jfif', 'Curated slide 5', 'Sikhara literally moans upright ihumb rising above fist hand its characteristic ICONOGRAPHY • Intent: Strength, steadiness, and resolve • Hand: Usually either hand • Position: All fingers fblded firmly into the palm; thumb extended upright Finger flexion: Firm flexion with the thumb held erect and controlled • Emotional tone: Confident, composed, and resolute • Common with: Deities holding bow (Rama, Forms of Siva, Devis), expressiVe iconographic gestures, and ritual hand formations five met a m', 'Shikhara Mudra (Śikhara Hasta) • Upright thumb rising above fist hand • ICONOGRAPHY • Intent: Strength, steadiness, and resolve • Hand: Usually either hand • Position: All fingers folded firmly into the palm; thumb extended upright • Finger flexion: Firm flexion with the thumb held erect and controlled • Emotional tone: Confident, composed, and resolute • Common with: Deities holding bow (Rama, Forms of Siva, Devis), expressive iconographic gestures, and ritual hand formations in Panchaloha bronze casting.', 'High-resolution iconography plate', 6);
INSERT INTO study_slides (id, study_id, slide_number, slide_title, image_url, thumbnail_url, caption, extracted_ocr_text, cleaned_text, visual_elements_summary, sort_order) VALUES ('sl_09b140bc6fdb', 's_ganesa_001', 6, 'Shikhara Mudra: Canonical Iconographic Hand Gesture', '/storage/images/ganesa-variations-in-iconography/upload_c3b616_mudra.jfif', '/storage/images/ganesa-variations-in-iconography/upload_c3b616_mudra.jfif', 'Curated slide 6', 'Sikhara literally moans upright ihumb rising above fist hand its characteristic ICONOGRAPHY', 'Śikhara (Mudra / Hasta): Literally denotes upright thumb rising above fist hand.', 'High-resolution iconography plate', 6);

-- -----------------------------------------------------------------------------
-- Table: taxonomy_types [T_ODS_TAXONOMY_TYPES (Classification Types)] (6 rows)
-- -----------------------------------------------------------------------------
INSERT INTO taxonomy_types (id, code, name, description) VALUES (1, 'divinity', 'Divinity', 'Primary and secondary divine figures');
INSERT INTO taxonomy_types (id, code, name, description) VALUES (2, 'form', 'Form', 'Specific identifiable iconographic forms');
INSERT INTO taxonomy_types (id, code, name, description) VALUES (3, 'iconographic_element', 'Iconographic Element', 'Attributes, gestures, postures, anatomical traits');
INSERT INTO taxonomy_types (id, code, name, description) VALUES (4, 'place', 'Place / Temple', 'Geographical and temple sites');
INSERT INTO taxonomy_types (id, code, name, description) VALUES (5, 'period_dynasty', 'Period / Dynasty', 'Historical and sculptural era');
INSERT INTO taxonomy_types (id, code, name, description) VALUES (6, 'source_reference', 'Source / Reference', 'Classical texts and collections');

-- -----------------------------------------------------------------------------
-- Table: taxonomy_terms [T_ODS_TAXONOMY_TERMS (Canonical Iconography Terms)] (37 rows)
-- -----------------------------------------------------------------------------
INSERT INTO taxonomy_terms (id, taxonomy_type_id, parent_id, canonical_name, iast_name, slug, description, dictionary_entry_id, place_id, period_id, is_active, display_order) VALUES ('t_ganesha', 1, NULL, 'Ganesha', 'Gaṇeśa', 'ganesha', 'Lord of beginnings with elephant head', NULL, NULL, NULL, TRUE, 1);
INSERT INTO taxonomy_terms (id, taxonomy_type_id, parent_id, canonical_name, iast_name, slug, description, dictionary_entry_id, place_id, period_id, is_active, display_order) VALUES ('t_siva', 1, NULL, 'Siva', 'Śiva', 'siva', 'Supreme Saiva deity', NULL, NULL, NULL, TRUE, 2);
INSERT INTO taxonomy_terms (id, taxonomy_type_id, parent_id, canonical_name, iast_name, slug, description, dictionary_entry_id, place_id, period_id, is_active, display_order) VALUES ('t_vishnu', 1, NULL, 'Vishnu', 'Viṣṇu', 'vishnu', 'Preserver deity', NULL, NULL, NULL, TRUE, 3);
INSERT INTO taxonomy_terms (id, taxonomy_type_id, parent_id, canonical_name, iast_name, slug, description, dictionary_entry_id, place_id, period_id, is_active, display_order) VALUES ('t_asana_group', 3, NULL, 'Asana & Sthana', 'Āsana & Sthāna', 'asana-sthana', 'Postures and bodily dispositions', NULL, NULL, NULL, TRUE, 1);
INSERT INTO taxonomy_terms (id, taxonomy_type_id, parent_id, canonical_name, iast_name, slug, description, dictionary_entry_id, place_id, period_id, is_active, display_order) VALUES ('t_anatomy_group', 3, NULL, 'Physical / Anatomical Feature', 'Śārīrika-lakṣaṇa', 'anatomical-features', 'Diagnostic physical traits', NULL, NULL, NULL, TRUE, 2);
INSERT INTO taxonomy_terms (id, taxonomy_type_id, parent_id, canonical_name, iast_name, slug, description, dictionary_entry_id, place_id, period_id, is_active, display_order) VALUES ('t_vahana_group', 3, NULL, 'Vahana', 'Vāhana', 'vahana', 'Animal mounts', NULL, NULL, NULL, TRUE, 3);
INSERT INTO taxonomy_terms (id, taxonomy_type_id, parent_id, canonical_name, iast_name, slug, description, dictionary_entry_id, place_id, period_id, is_active, display_order) VALUES ('t_asina', 3, 't_asana_group', 'Asina', 'Āsīna', 'asina', 'General seated posture', 'd1', NULL, NULL, TRUE, 1);
INSERT INTO taxonomy_terms (id, taxonomy_type_id, parent_id, canonical_name, iast_name, slug, description, dictionary_entry_id, place_id, period_id, is_active, display_order) VALUES ('t_sthanaka', 3, 't_asana_group', 'Sthanaka', 'Sthānaka', 'sthanaka', 'Standing posture', NULL, NULL, NULL, TRUE, 2);
INSERT INTO taxonomy_terms (id, taxonomy_type_id, parent_id, canonical_name, iast_name, slug, description, dictionary_entry_id, place_id, period_id, is_active, display_order) VALUES ('t_nrtta', 3, 't_asana_group', 'Nrtta', 'Nṛtta', 'nrtta', 'Dancing posture', NULL, NULL, NULL, TRUE, 3);
INSERT INTO taxonomy_terms (id, taxonomy_type_id, parent_id, canonical_name, iast_name, slug, description, dictionary_entry_id, place_id, period_id, is_active, display_order) VALUES ('t_lalitasana', 3, 't_asana_group', 'Lalitasana', 'Lalitāsana', 'lalitasana', 'Royal ease posture', 'd2', NULL, NULL, TRUE, 4);
INSERT INTO taxonomy_terms (id, taxonomy_type_id, parent_id, canonical_name, iast_name, slug, description, dictionary_entry_id, place_id, period_id, is_active, display_order) VALUES ('t_sukhasana', 3, 't_asana_group', 'Sukhasana', 'Sukhāsana', 'sukhasana', 'Comfortable sitting pose', 'd3', NULL, NULL, TRUE, 5);
INSERT INTO taxonomy_terms (id, taxonomy_type_id, parent_id, canonical_name, iast_name, slug, description, dictionary_entry_id, place_id, period_id, is_active, display_order) VALUES ('t_padmasana', 3, 't_asana_group', 'Padmasana', 'Padmāsana', 'padmasana', 'Full lotus posture', NULL, NULL, NULL, TRUE, 6);
INSERT INTO taxonomy_terms (id, taxonomy_type_id, parent_id, canonical_name, iast_name, slug, description, dictionary_entry_id, place_id, period_id, is_active, display_order) VALUES ('t_ardhaparyankasana', 3, 't_asana_group', 'Ardhaparyankasana', 'Ardhaparyaṅkāsana', 'ardhaparyankasana', 'Half cross-legged posture', 'd4', NULL, NULL, TRUE, 7);
INSERT INTO taxonomy_terms (id, taxonomy_type_id, parent_id, canonical_name, iast_name, slug, description, dictionary_entry_id, place_id, period_id, is_active, display_order) VALUES ('t_bhadrasana', 3, 't_asana_group', 'Bhadrasana', 'Bhadrāsana', 'bhadrasana', 'Auspicious symmetrical seated posture', 'd5', NULL, NULL, TRUE, 8);
INSERT INTO taxonomy_terms (id, taxonomy_type_id, parent_id, canonical_name, iast_name, slug, description, dictionary_entry_id, place_id, period_id, is_active, display_order) VALUES ('t_dvibhuja', 3, 't_anatomy_group', 'Dvibhuja', 'Dvibhuja', 'dvibhuja', 'Two-armed form', NULL, NULL, NULL, TRUE, 1);
INSERT INTO taxonomy_terms (id, taxonomy_type_id, parent_id, canonical_name, iast_name, slug, description, dictionary_entry_id, place_id, period_id, is_active, display_order) VALUES ('t_caturbhuja', 3, 't_anatomy_group', 'Caturbhuja', 'Caturbhuja', 'caturbhuja', 'Four-armed form', NULL, NULL, NULL, TRUE, 2);
INSERT INTO taxonomy_terms (id, taxonomy_type_id, parent_id, canonical_name, iast_name, slug, description, dictionary_entry_id, place_id, period_id, is_active, display_order) VALUES ('t_sadbhuja', 3, 't_anatomy_group', 'Sadbhuja', 'Ṣaḍbhuja', 'sadbhuja', 'Six-armed form', NULL, NULL, NULL, TRUE, 3);
INSERT INTO taxonomy_terms (id, taxonomy_type_id, parent_id, canonical_name, iast_name, slug, description, dictionary_entry_id, place_id, period_id, is_active, display_order) VALUES ('t_astabhuja', 3, 't_anatomy_group', 'Astabhuja', 'Aṣṭabhuja', 'astabhuja', 'Eight-armed form', NULL, NULL, NULL, TRUE, 4);
INSERT INTO taxonomy_terms (id, taxonomy_type_id, parent_id, canonical_name, iast_name, slug, description, dictionary_entry_id, place_id, period_id, is_active, display_order) VALUES ('t_sodasabhuja', 3, 't_anatomy_group', 'Sodasabhuja', 'Ṣoḍaśabhuja', 'sodasabhuja', 'Sixteen-armed form', NULL, NULL, NULL, TRUE, 5);
INSERT INTO taxonomy_terms (id, taxonomy_type_id, parent_id, canonical_name, iast_name, slug, description, dictionary_entry_id, place_id, period_id, is_active, display_order) VALUES ('t_vamavarta', 3, 't_anatomy_group', 'Vamavarta', 'Vāmāvarta', 'vamavarta', 'Left-turning trunk', NULL, NULL, NULL, TRUE, 6);
INSERT INTO taxonomy_terms (id, taxonomy_type_id, parent_id, canonical_name, iast_name, slug, description, dictionary_entry_id, place_id, period_id, is_active, display_order) VALUES ('t_daksinavarta', 3, 't_anatomy_group', 'Daksinavarta', 'Dakṣiṇāvarta', 'daksinavarta', 'Right-turning trunk', NULL, NULL, NULL, TRUE, 7);
INSERT INTO taxonomy_terms (id, taxonomy_type_id, parent_id, canonical_name, iast_name, slug, description, dictionary_entry_id, place_id, period_id, is_active, display_order) VALUES ('t_trishunda', 3, 't_anatomy_group', 'Trishunda', 'Triśuṇḍa', 'trishunda', 'Three trunks', 'd6', NULL, NULL, TRUE, 8);
INSERT INTO taxonomy_terms (id, taxonomy_type_id, parent_id, canonical_name, iast_name, slug, description, dictionary_entry_id, place_id, period_id, is_active, display_order) VALUES ('t_human_headed', 3, 't_anatomy_group', 'Human-headed Form', 'Naramukha', 'human-headed', 'Human face of Adi Vinayaka', NULL, NULL, NULL, TRUE, 9);
INSERT INTO taxonomy_terms (id, taxonomy_type_id, parent_id, canonical_name, iast_name, slug, description, dictionary_entry_id, place_id, period_id, is_active, display_order) VALUES ('t_trunkless', 3, 't_anatomy_group', 'Trunkless Form', 'Ashunda', 'trunkless', 'Trunkless form of Garh Ganesh', NULL, NULL, NULL, TRUE, 10);
INSERT INTO taxonomy_terms (id, taxonomy_type_id, parent_id, canonical_name, iast_name, slug, description, dictionary_entry_id, place_id, period_id, is_active, display_order) VALUES ('t_musika', 3, 't_vahana_group', 'Musika', 'Mūṣika', 'musika', 'Mouse / rat mount of Ganesha', NULL, NULL, NULL, TRUE, 1);
INSERT INTO taxonomy_terms (id, taxonomy_type_id, parent_id, canonical_name, iast_name, slug, description, dictionary_entry_id, place_id, period_id, is_active, display_order) VALUES ('t_mayura', 3, 't_vahana_group', 'Mayura', 'Mayūra', 'mayura', 'Peacock mount of Trishunda Ganapati', NULL, NULL, NULL, TRUE, 2);
INSERT INTO taxonomy_terms (id, taxonomy_type_id, parent_id, canonical_name, iast_name, slug, description, dictionary_entry_id, place_id, period_id, is_active, display_order) VALUES ('t_simha', 3, 't_vahana_group', 'Simha', 'Siṃha', 'simha', 'Lion mount of Heramba Ganapati', NULL, NULL, NULL, TRUE, 3);
INSERT INTO taxonomy_terms (id, taxonomy_type_id, parent_id, canonical_name, iast_name, slug, description, dictionary_entry_id, place_id, period_id, is_active, display_order) VALUES ('t_form_adi_vinayaka', 2, NULL, 'Adi Vinayaka', 'Ādi Vināyaka', 'adi-vinayaka', 'Primordial human-faced form', NULL, 'p1', NULL, TRUE, 1);
INSERT INTO taxonomy_terms (id, taxonomy_type_id, parent_id, canonical_name, iast_name, slug, description, dictionary_entry_id, place_id, period_id, is_active, display_order) VALUES ('t_form_trishund', 2, NULL, 'Trishund Ganapati', 'Triśuṇḍa Gaṇapati', 'trishund-ganapati', 'Three-trunked form on peacock', NULL, 'p2', NULL, TRUE, 2);
INSERT INTO taxonomy_terms (id, taxonomy_type_id, parent_id, canonical_name, iast_name, slug, description, dictionary_entry_id, place_id, period_id, is_active, display_order) VALUES ('t_form_garh_ganesh', 2, NULL, 'Garh Ganesh', 'Gaṛh Gaṇeśa', 'garh-ganesh', 'Trunkless form from Jaipur', NULL, 'p3', NULL, TRUE, 3);
INSERT INTO taxonomy_terms (id, taxonomy_type_id, parent_id, canonical_name, iast_name, slug, description, dictionary_entry_id, place_id, period_id, is_active, display_order) VALUES ('t_mudra', 3, NULL, 'Mudra', 'Mudrā', 'mudra', 'Iconographic hand gestures and ritual hastas in sacred sculpture', NULL, NULL, NULL, TRUE, 0);
INSERT INTO taxonomy_terms (id, taxonomy_type_id, parent_id, canonical_name, iast_name, slug, description, dictionary_entry_id, place_id, period_id, is_active, display_order) VALUES ('t_shikhara_mudra', 3, NULL, 'Shikhara Mudra', 'Śikhara Mudrā', 'shikhara-mudra', 'Upright thumb gesture denoting firmness, resolve, and holding bow or weapons', NULL, NULL, NULL, TRUE, 0);
INSERT INTO taxonomy_terms (id, taxonomy_type_id, parent_id, canonical_name, iast_name, slug, description, dictionary_entry_id, place_id, period_id, is_active, display_order) VALUES ('t_abhaya_mudra', 3, NULL, 'Abhaya Mudra', 'Abhaya Mudrā', 'abhaya-mudra', 'Gesture of fearlessness, protection, and divine reassurance', NULL, NULL, NULL, TRUE, 0);
INSERT INTO taxonomy_terms (id, taxonomy_type_id, parent_id, canonical_name, iast_name, slug, description, dictionary_entry_id, place_id, period_id, is_active, display_order) VALUES ('t_varada_mudra', 3, NULL, 'Varada Mudra', 'Varada Mudrā', 'varada-mudra', 'Gesture of dispensing boons, grace, and divine charity', NULL, NULL, NULL, TRUE, 0);
INSERT INTO taxonomy_terms (id, taxonomy_type_id, parent_id, canonical_name, iast_name, slug, description, dictionary_entry_id, place_id, period_id, is_active, display_order) VALUES ('t_chin_mudra', 3, NULL, 'Chin Mudra', 'Cin Mudrā', 'chin-mudra', 'Gesture of spiritual wisdom, consciousness, and contemplation (Jnana/Vitarka)', NULL, NULL, NULL, TRUE, 0);
INSERT INTO taxonomy_terms (id, taxonomy_type_id, parent_id, canonical_name, iast_name, slug, description, dictionary_entry_id, place_id, period_id, is_active, display_order) VALUES ('t_dhyana_mudra', 3, NULL, 'Dhyana Mudra', 'Dhyāna Mudrā', 'dhyana-mudra', 'Gesture of deep meditation and yogic absorption (Samadhi)', NULL, NULL, NULL, TRUE, 0);
INSERT INTO taxonomy_terms (id, taxonomy_type_id, parent_id, canonical_name, iast_name, slug, description, dictionary_entry_id, place_id, period_id, is_active, display_order) VALUES ('t_gajahasta', 3, NULL, 'Gajahasta', 'Gajahasta', 'gajahasta', 'Elephant-trunk gesture across the chest in cosmic dance iconography (Nataraja)', NULL, NULL, NULL, TRUE, 0);

-- -----------------------------------------------------------------------------
-- Table: term_aliases [T_ODS_TERM_ALIASES (Multilingual Transliterations & OCR Variants)] (72 rows)
-- -----------------------------------------------------------------------------
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('a1', 't_ganesha', 'Ganesa', 'spelling_variant', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('a2', 't_ganesha', 'Gaṇeśa', 'iast_transliteration', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('a3', 't_ganesha', 'Ganapati', 'spelling_variant', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('a4', 't_ganesha', 'Vinayaka', 'spelling_variant', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('a5', 't_ganesha', 'Pillayar', 'regional_vernacular', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('a6', 't_ganesha', 'Elephant God', 'english_translation', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('a7', 't_ganesha', 'GaQeSa', 'ocr_artifact', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('a8', 't_asina', 'Seated', 'english_translation', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('a9', 't_asina', 'Sitting', 'english_translation', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('a10', 't_asina', 'Āsīna', 'iast_transliteration', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('a11', 't_asina', 'ÄsTna', 'ocr_artifact', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('a12', 't_musika', 'Mushika', 'spelling_variant', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('a13', 't_musika', 'Mouse', 'english_translation', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('a14', 't_musika', 'Rat', 'english_translation', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('a15', 't_trishunda', 'Three trunks', 'english_translation', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('a16', 't_trishunda', 'Triśuṇḍa', 'iast_transliteration', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('a17', 't_trishunda', 'Trishund', 'spelling_variant', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('a18', 't_lalitasana', 'Royal ease', 'english_translation', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('a19', 't_sukhasana', 'Easy pose', 'english_translation', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('a20', 't_padmasana', 'Lotus pose', 'english_translation', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('a21', 't_vamavarta', 'Left turning trunk', 'english_translation', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('a22', 't_daksinavarta', 'Right turning trunk', 'english_translation', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('a23', 't_musika', 'Mooshika', 'phonetic_transliteration', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('a24', 't_musika', 'Mooshik', 'phonetic_transliteration', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('a25', 't_musika', 'Mooshikam', 'phonetic_transliteration', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('a26', 't_musika', 'Mūṣikavāhana', 'compound_iconographic_attribute', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('a27', 't_musika', 'Musikavahana', 'compound_iconographic_attribute', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('a28', 't_musika', 'Mooshikavahana', 'compound_iconographic_attribute', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('a29', 't_musika', 'Mushikavahana', 'compound_iconographic_attribute', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('a30', 't_musika', 'Mü$kavähana', 'ocr_artifact', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('a31', 't_musika', 'Mūṣika', 'iast_transliteration', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('a32', 't_ganesha', 'Ganesh', 'spelling_variant', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('a33', 't_ganesha', 'Ganapathy', 'spelling_variant', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('a34', 't_ganesha', 'Vigneshwara', 'spelling_variant', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('a35', 't_siva', 'Shiva', 'spelling_variant', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('a36', 't_siva', 'Sheeva', 'phonetic_transliteration', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('al_t_mudra_mudra', 't_mudra', 'Mudra', 'canonical', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('al_t_mudra_mudras', 't_mudra', 'Mudras', 'plural', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('al_t_mudra_hasta', 't_mudra', 'Hasta', 'synonym', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('al_t_mudra_hastas', 't_mudra', 'Hastas', 'synonym', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('al_t_mudra_hand_gesture', 't_mudra', 'Hand Gesture', 'english_gloss', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('al_t_mudra_hand_gestures', 't_mudra', 'Hand Gestures', 'english_gloss', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('al_t_mudra_iconographic_gestures', 't_mudra', 'Iconographic Gestures', 'english_gloss', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('al_t_mudra_ritual_hand_formations', 't_mudra', 'Ritual Hand Formations', 'english_gloss', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('al_t_mudra_gesture', 't_mudra', 'Gesture', 'generic', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('al_t_mudra_gestures', 't_mudra', 'Gestures', 'generic', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('al_t_shikhara_mudra_shikhara_mudra', 't_shikhara_mudra', 'Shikhara Mudra', 'canonical', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('al_t_shikhara_mudra_sikhara', 't_shikhara_mudra', 'Sikhara', 'common_spelling', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('al_t_shikhara_mudra_shikhara', 't_shikhara_mudra', 'Shikhara', 'common_spelling', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('al_t_shikhara_mudra_sikhara_mudra', 't_shikhara_mudra', 'Sikhara Mudra', 'common_spelling', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('al_t_shikhara_mudra_sikhara_hasta', 't_shikhara_mudra', 'Sikhara Hasta', 'synonym', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('al_t_shikhara_mudra_shikhara_hasta', 't_shikhara_mudra', 'Shikhara Hasta', 'synonym', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('al_t_shikhara_mudra_upright_thumb', 't_shikhara_mudra', 'Upright Thumb', 'descriptive', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('al_t_abhaya_mudra_abhaya_mudra', 't_abhaya_mudra', 'Abhaya Mudra', 'canonical', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('al_t_abhaya_mudra_abhaya', 't_abhaya_mudra', 'Abhaya', 'short_form', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('al_t_abhaya_mudra_abhayamudra', 't_abhaya_mudra', 'Abhayamudra', 'compound', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('al_t_abhaya_mudra_abhaya_hasta', 't_abhaya_mudra', 'Abhaya Hasta', 'synonym', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('al_t_abhaya_mudra_gesture_of_fearlessness', 't_abhaya_mudra', 'Gesture of Fearlessness', 'english_gloss', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('al_t_abhaya_mudra_protection_gesture', 't_abhaya_mudra', 'Protection Gesture', 'english_gloss', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('al_t_varada_mudra_varada_mudra', 't_varada_mudra', 'Varada Mudra', 'canonical', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('al_t_varada_mudra_varada', 't_varada_mudra', 'Varada', 'short_form', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('al_t_varada_mudra_varadamudra', 't_varada_mudra', 'Varadamudra', 'compound', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('al_t_varada_mudra_gesture_of_boon-giving', 't_varada_mudra', 'Gesture of Boon-Giving', 'english_gloss', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('al_t_chin_mudra_chin_mudra', 't_chin_mudra', 'Chin Mudra', 'canonical', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('al_t_chin_mudra_jnana_mudra', 't_chin_mudra', 'Jnana Mudra', 'synonym', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('al_t_chin_mudra_vitarka_mudra', 't_chin_mudra', 'Vitarka Mudra', 'synonym', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('al_t_chin_mudra_cin_mudra', 't_chin_mudra', 'Cin Mudra', 'iast_approx', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('al_t_dhyana_mudra_dhyana_mudra', 't_dhyana_mudra', 'Dhyana Mudra', 'canonical', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('al_t_dhyana_mudra_samadhi_mudra', 't_dhyana_mudra', 'Samadhi Mudra', 'synonym', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('al_t_gajahasta_gajahasta', 't_gajahasta', 'Gajahasta', 'canonical', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('al_t_gajahasta_karihasta', 't_gajahasta', 'Karihasta', 'synonym', TRUE);
INSERT INTO term_aliases (id, term_id, alias, alias_type, is_searchable) VALUES ('al_t_gajahasta_dandahasta', 't_gajahasta', 'Dandahasta', 'synonym', TRUE);

-- -----------------------------------------------------------------------------
-- Table: study_taxonomy_mappings [T_ODS_STUDY_TAXONOMY (Verified Thematic Linkages)] (20 rows)
-- -----------------------------------------------------------------------------
INSERT INTO study_taxonomy_mappings (id, study_id, term_id, relevance_level, confidence_score, slide_numbers, curator_verified, curator_notes) VALUES ('m1', 's_ganesa_001', 't_ganesha', 'primary_subject', 1.0, '[1, 2, 3, 4]', TRUE, 'Primary divinity of this visual study');
INSERT INTO study_taxonomy_mappings (id, study_id, term_id, relevance_level, confidence_score, slide_numbers, curator_verified, curator_notes) VALUES ('m2', 's_ganesa_001', 't_asina', 'materially_discussed', 1.0, '[2, 3, 4]', TRUE, 'Asina posture analyzed extensively');
INSERT INTO study_taxonomy_mappings (id, study_id, term_id, relevance_level, confidence_score, slide_numbers, curator_verified, curator_notes) VALUES ('m3', 's_ganesa_001', 't_lalitasana', 'materially_discussed', 1.0, '[4]', TRUE, 'Lalitasana illustrated in detail');
INSERT INTO study_taxonomy_mappings (id, study_id, term_id, relevance_level, confidence_score, slide_numbers, curator_verified, curator_notes) VALUES ('m4', 's_ganesa_001', 't_sukhasana', 'materially_discussed', 1.0, '[4]', TRUE, 'Sukhasana defined in slide 4');
INSERT INTO study_taxonomy_mappings (id, study_id, term_id, relevance_level, confidence_score, slide_numbers, curator_verified, curator_notes) VALUES ('m5', 's_ganesa_001', 't_padmasana', 'materially_discussed', 1.0, '[4]', TRUE, 'Padmasana defined in slide 4');
INSERT INTO study_taxonomy_mappings (id, study_id, term_id, relevance_level, confidence_score, slide_numbers, curator_verified, curator_notes) VALUES ('m6', 's_ganesa_001', 't_bhadrasana', 'materially_discussed', 1.0, '[4]', TRUE, 'Bhadrasana defined in slide 4');
INSERT INTO study_taxonomy_mappings (id, study_id, term_id, relevance_level, confidence_score, slide_numbers, curator_verified, curator_notes) VALUES ('m7', 's_ganesa_001', 't_trishunda', 'materially_discussed', 1.0, '[2, 3]', TRUE, 'Trishunda three-trunked form');
INSERT INTO study_taxonomy_mappings (id, study_id, term_id, relevance_level, confidence_score, slide_numbers, curator_verified, curator_notes) VALUES ('m8', 's_ganesa_001', 't_vamavarta', 'materially_discussed', 1.0, '[2, 3]', TRUE, 'Left-turning trunk');
INSERT INTO study_taxonomy_mappings (id, study_id, term_id, relevance_level, confidence_score, slide_numbers, curator_verified, curator_notes) VALUES ('m9', 's_ganesa_001', 't_daksinavarta', 'materially_discussed', 1.0, '[2, 3]', TRUE, 'Right-turning trunk');
INSERT INTO study_taxonomy_mappings (id, study_id, term_id, relevance_level, confidence_score, slide_numbers, curator_verified, curator_notes) VALUES ('m10', 's_ganesa_001', 't_musika', 'materially_discussed', 1.0, '[2, 3]', TRUE, 'Musika mount');
INSERT INTO study_taxonomy_mappings (id, study_id, term_id, relevance_level, confidence_score, slide_numbers, curator_verified, curator_notes) VALUES ('m_e5c56d35', 's_ganesa_001', 't_lalitasana', 'materially_discussed', 0.95, '[5]', TRUE, 'Curator approved via Visual OCR Studio');
INSERT INTO study_taxonomy_mappings (id, study_id, term_id, relevance_level, confidence_score, slide_numbers, curator_verified, curator_notes) VALUES ('m_992838bc', 's_ganesa_001', 't_asina', 'materially_discussed', 0.95, '[5]', TRUE, 'Curator approved via Visual OCR Studio');
INSERT INTO study_taxonomy_mappings (id, study_id, term_id, relevance_level, confidence_score, slide_numbers, curator_verified, curator_notes) VALUES ('m_4f1a3fa4', 's_ganesa_001', 't_ganesha', 'materially_discussed', 0.95, '[5]', TRUE, 'Curator approved via Visual OCR Studio');
INSERT INTO study_taxonomy_mappings (id, study_id, term_id, relevance_level, confidence_score, slide_numbers, curator_verified, curator_notes) VALUES ('m_681f5b96', 's_ganesa_001', 't_siva', 'materially_discussed', 0.98, '[5]', TRUE, 'Curator approved via Visual OCR Studio');
INSERT INTO study_taxonomy_mappings (id, study_id, term_id, relevance_level, confidence_score, slide_numbers, curator_verified, curator_notes) VALUES ('m_ganesa_shikhara', 's_ganesa_001', 't_shikhara_mudra', 'primary_subject', 0.98, '[6]', TRUE, 'Uploaded curated slide for Shikhara Mudra');
INSERT INTO study_taxonomy_mappings (id, study_id, term_id, relevance_level, confidence_score, slide_numbers, curator_verified, curator_notes) VALUES ('m_ganesa_mudra', 's_ganesa_001', 't_mudra', 'materially_discussed', 0.95, '[6]', TRUE, 'Iconographic hand gesture analysis');
INSERT INTO study_taxonomy_mappings (id, study_id, term_id, relevance_level, confidence_score, slide_numbers, curator_verified, curator_notes) VALUES ('m_nataraja_abhaya', 's_nataraja_002', 't_abhaya_mudra', 'primary_subject', 0.99, '[1,2,3,4]', TRUE, 'Nataraja front right hand in Abhaya Mudra offering protection');
INSERT INTO study_taxonomy_mappings (id, study_id, term_id, relevance_level, confidence_score, slide_numbers, curator_verified, curator_notes) VALUES ('m_nataraja_gajahasta', 's_nataraja_002', 't_gajahasta', 'primary_subject', 0.98, '[1,2,3,4]', TRUE, 'Nataraja front left arm sweeping across in Gajahasta pointing to lifted foot');
INSERT INTO study_taxonomy_mappings (id, study_id, term_id, relevance_level, confidence_score, slide_numbers, curator_verified, curator_notes) VALUES ('m_nataraja_mudra', 's_nataraja_002', 't_mudra', 'materially_discussed', 0.96, '[1,2,3,4]', TRUE, 'Cosmic dance mudras');
INSERT INTO study_taxonomy_mappings (id, study_id, term_id, relevance_level, confidence_score, slide_numbers, curator_verified, curator_notes) VALUES ('m_b3781d11', 's_ganesa_001', 't_shikhara_mudra', 'materially_discussed', 0.98, '[6]', TRUE, 'Curator approved via Visual OCR Studio');

-- -----------------------------------------------------------------------------
-- Table: dictionary_entries [T_ODS_DICTIONARY (IAST Sanskrit Glossary)] (6 rows)
-- -----------------------------------------------------------------------------
INSERT INTO dictionary_entries (id, slug, headword, iast_headword, part_of_speech, etymology, definition, extended_notes, created_at, updated_at, created_by, updated_by) VALUES ('d1', 'asina', 'Asina', 'Āsīna', 'participle / adjective', 'From Sanskrit root ās (to sit, rest)', 'Seated posture; a generic term for any iconographic form depicted in a sitting position.', 'Contrasts with sthānaka (standing) and nṛtta (dancing). Includes padmāsana, sukhāsana, lalitāsana, ardhaparyaṅkāsana, and bhadrāsana.', '2026-09-13 12:01:18.838984', '2026-09-13 12:01:18.848210', 'curator', 'curator');
INSERT INTO dictionary_entries (id, slug, headword, iast_headword, part_of_speech, etymology, definition, extended_notes, created_at, updated_at, created_by, updated_by) VALUES ('d2', 'lalitasana', 'Lalitasana', 'Lalitāsana', 'noun, neuter', 'From Sanskrit lalita (charming, graceful) + āsana', 'The posture of royal ease, wherein one leg is folded on seat while the other hangs down gracefully.', 'Quintessential posture for benevolent divinities including Ganesha and Devi.', '2026-09-13 12:01:18.838984', '2026-09-13 12:01:18.848210', 'curator', 'curator');
INSERT INTO dictionary_entries (id, slug, headword, iast_headword, part_of_speech, etymology, definition, extended_notes, created_at, updated_at, created_by, updated_by) VALUES ('d3', 'sukhasana', 'Sukhasana', 'Sukhāsana', 'noun, neuter', 'From sukha (comfort) + āsana', 'Comfortable seated posture; relaxed informal disposition of legs.', 'Observed in Siva Somaskanda bronzes.', '2026-09-13 12:01:18.838984', '2026-09-13 12:01:18.848210', 'curator', 'curator');
INSERT INTO dictionary_entries (id, slug, headword, iast_headword, part_of_speech, etymology, definition, extended_notes, created_at, updated_at, created_by, updated_by) VALUES ('d4', 'ardhaparyankasana', 'Ardhaparyankasana', 'Ardhaparyaṅkāsana', 'noun, neuter', 'From ardha + paryaṅka + āsana', 'Seated posture with one leg folded and one knee elevated with pendant foot.', 'Frequently used in Agamic descriptions of meditative royalty.', '2026-09-13 12:01:18.838984', '2026-09-13 12:01:18.848210', 'curator', 'curator');
INSERT INTO dictionary_entries (id, slug, headword, iast_headword, part_of_speech, etymology, definition, extended_notes, created_at, updated_at, created_by, updated_by) VALUES ('d5', 'bhadrasana', 'Bhadrasana', 'Bhadrāsana', 'noun, neuter', 'From bhadra (auspicious) + āsana', 'Majestic sitting posture where feet rest on a support or soles meet symmetrically.', 'Classical imperial seated posture in Shilpa Shastras.', '2026-09-13 12:01:18.838984', '2026-09-13 12:01:18.848210', 'curator', 'curator');
INSERT INTO dictionary_entries (id, slug, headword, iast_headword, part_of_speech, etymology, definition, extended_notes, created_at, updated_at, created_by, updated_by) VALUES ('d6', 'trishunda', 'Trishunda', 'Triśuṇḍa', 'adjective / noun', 'From tri (three) + śuṇḍā (trunk)', 'Possessing three elephant trunks; rare iconographic manifestation.', 'Exemplified in Pune Trishund temple.', '2026-09-13 12:01:18.838984', '2026-09-13 12:01:18.848210', 'curator', 'curator');

-- -----------------------------------------------------------------------------
-- Table: doc_ref_catalog [T_ODS_DOC_CATALOG (Primary Textual Reference Catalog)] (5 rows)
-- -----------------------------------------------------------------------------
INSERT INTO doc_ref_catalog (doc_ref, doc_name, corpus, section, author_or_tradition, language, applicability_to_iconography, created_at, updated_at, created_by, updated_by) VALUES ('DOC_REF_001', 'Mānasāra Śilpa Śāstra', 'Agama & Vastu Shastra Corpus', 'Chapter 51-56: Tālamāna & Pratima Lakshana', 'Maharshi Mānasāra', 'Sanskrit (IAST)', 'Foundational text for iconometric proportions (Navatala, Dasatala) and divine bronze casting.', '2026-09-13 12:01:55.732930', '2026-09-13 12:01:55.732930', 'system', 'system');
INSERT INTO doc_ref_catalog (doc_ref, doc_name, corpus, section, author_or_tradition, language, applicability_to_iconography, created_at, updated_at, created_by, updated_by) VALUES ('DOC_REF_002', 'Śilparatna', 'South Indian Silpa Corpus', 'Part II: Iconography of Devas & Devis', 'Śrīkumāra of Kerala (16th C CE)', 'Sanskrit', 'Detailed treatises on mudras, ayudhas, postures, and Panchaloha alloy mixing formulas.', '2026-09-13 12:01:55.799086', '2026-09-13 12:01:55.799086', 'system', 'system');
INSERT INTO doc_ref_catalog (doc_ref, doc_name, corpus, section, author_or_tradition, language, applicability_to_iconography, created_at, updated_at, created_by, updated_by) VALUES ('DOC_REF_003', 'Kāraṇāgama', 'Saiva Agamic Corpus', 'Kriya Pada: Murti Laksana', 'Saiva Siddhanta Tradition', 'Sanskrit (Grantha Script)', 'Prescribes ritual dimensions, postures, and iconographic marks for Siva, Ganesha, and Skanda.', '2026-09-13 12:01:55.869151', '2026-09-13 12:01:55.869151', 'system', 'system');
INSERT INTO doc_ref_catalog (doc_ref, doc_name, corpus, section, author_or_tradition, language, applicability_to_iconography, created_at, updated_at, created_by, updated_by) VALUES ('DOC_REF_004', 'Mayamata', 'Vastu & Silpa Shastra Corpus', 'Chapters 34-36: Sculptural Proportions', 'Mayamuni', 'Sanskrit', 'Comprehensive manual on architectural sculpture, bronze casting, and iconographic symmetry.', '2026-09-13 12:01:55.937201', '2026-09-13 12:01:55.937201', 'system', 'system');
INSERT INTO doc_ref_catalog (doc_ref, doc_name, corpus, section, author_or_tradition, language, applicability_to_iconography, created_at, updated_at, created_by, updated_by) VALUES ('DOC_REF_005', 'Elements of Hindu Iconography', 'Modern Epigraphical Corpus', 'Volumes I & II', 'T.A. Gopinatha Rao (1914)', 'English / Sanskrit Citations', 'Pioneering academic baseline reference cross-referencing Agamic texts with Chola/Pallava bronzes.', '2026-09-13 12:01:56.009609', '2026-09-13 12:01:56.009609', 'system', 'system');

-- -----------------------------------------------------------------------------
-- Table: places [T_ODS_PLACES (Sacred Temples & Archaeological Sites)] (3 rows)
-- -----------------------------------------------------------------------------
INSERT INTO places (id, slug, name, native_name, temple_name, deity_enshrined, tradition, town_city, district, state, country, notes) VALUES ('p1', 'adi-vinayaka-thilatharpanapuri', 'Adi Vinayaka Temple, Thilatharpanapuri', 'ஆதி விநாயகர்', 'Muktheeswarar Temple complex', 'Nara-mukha Ganesha', 'Saiva / Ganapatya', 'Thilatharpanapuri', 'Tiruvarur', 'Tamil Nadu', 'India', 'Human-faced Ganesha without elephant head.');
INSERT INTO places (id, slug, name, native_name, temple_name, deity_enshrined, tradition, town_city, district, state, country, notes) VALUES ('p2', 'trishund-ganapati-pune', 'Trishund Mayureshwar Ganapati, Pune', 'त्रिशुंड गणपती', 'Trishund Ganapati Temple', 'Three-trunked Ganesha on peacock', 'Ganapatya', 'Pune', 'Pune', 'Maharashtra', 'India', '18th-century temple in Somwar Peth featuring 3 trunks on peacock mount.');
INSERT INTO places (id, slug, name, native_name, temple_name, deity_enshrined, tradition, town_city, district, state, country, notes) VALUES ('p3', 'garh-ganesh-jaipur', 'Garh Ganesh Temple, Jaipur', 'गढ़ गणेश', 'Garh Ganesh Mandir', 'Trunkless Ganesha', 'Ganapatya', 'Jaipur', 'Jaipur', 'Rajasthan', 'India', 'Hilltop temple showing Ganesha in child-like trunkless form.');

-- -----------------------------------------------------------------------------
-- Table: slide_ocr_data [T_RAW_SLIDE_OCR (Raw Deep OCR Engine Tokens)] (3 rows)
-- -----------------------------------------------------------------------------
INSERT INTO slide_ocr_data (id, slide_id, ocr_engine, language_tag, raw_ocr_output, normalized_text, word_count, confidence_avg, tokens_json) VALUES ('ocr_sl_8b18a50ad6b8', 'sl_8b18a50ad6b8', 'windows_media_ocr', 'en-US', 'ICONOGRAPHY POSTURAL VARIATIONS ÄSiNA I SITTING In the äsrna form, Ganesa is represented seated in a stable and composed posturer with the legs arranged in several ways according to the specific iconographic form. He in padmäsana (lotus may sit posture), sukhäsana (easy posture), lalitäsana (posture of royal ease), or ardhaparyahkäsana (with one leg — pendant and the other drawn up). He may also be shown in bhadräsana (a formal seated posture, generally with both feet placed on a support or with the legs arranged symmetrically). The characteristic elephant head, large ears and prominent rounded belly are retained, while the number ¯ of arms, gestures and attributes may vary according to the specific iconographic form. FIVE METAL MASONRY fivemetalmasonry.com', 'ICONOGRAPHY POSTURAL VARIATIONS ĀSĪNA I SITTING In the āsīna form, Ganesa is represented seated in a stable and composed posturer with the legs arranged in several ways according to the specific iconographic form. He in padmāsana (lotus may sit posture), sukhāsana (easy posture), lalitāsana (posture of royal ease), or ardhaparyaṅkāsana (with one leg — pendant and the other drawn up). He may also be shown in bhadrāsana (a formal seated posture, generally with both feet placed on a support or with the legs arranged symmetrically). The characteristic elephant head, large ears and prominent rounded belly are retained, while the number ¯ of arms, gestures and attributes may vary according to the specific iconographic form. FIVE METAL MASONRY fivemetalmasonry.com', 118, 0.96, '{}');
INSERT INTO slide_ocr_data (id, slide_id, ocr_engine, language_tag, raw_ocr_output, normalized_text, word_count, confidence_avg, tokens_json) VALUES ('ocr_sl_cc51fdf0d4d3', 'sl_cc51fdf0d4d3', 'windows_media_ocr', 'en-US', 'Sikhara literally moans upright ihumb rising above fist hand its characteristic ICONOGRAPHY • Intent: Strength, steadiness, and resolve • Hand: Usually either hand • Position: All fingers fblded firmly into the palm; thumb extended upright Finger flexion: Firm flexion with the thumb held erect and controlled • Emotional tone: Confident, composed, and resolute • Common with: Deities holding bow (Rama, Forms of Siva, Devis), expressiVe iconographic gestures, and ritual hand formations five met a m', 'Sikhara literally moans upright ihumb rising above fist hand its characteristic ICONOGRAPHY • Intent: Strength, steadiness, and resolve • Hand: Usually either hand • Position: All fingers fblded firmly into the palm; thumb extended upright Finger flexion: Firm flexion with the thumb held erect and controlled • Emotional tone: Confident, composed, and resolute • Common with: Deities holding bow (Rama, Forms of Siva, Devis), expressiVe iconographic gestures, and ritual hand formations five met a m', 75, 0.96, '{}');
INSERT INTO slide_ocr_data (id, slide_id, ocr_engine, language_tag, raw_ocr_output, normalized_text, word_count, confidence_avg, tokens_json) VALUES ('ocr_sl_09b140bc6fdb', 'sl_09b140bc6fdb', 'windows_media_ocr', 'en-US', 'Sikhara literally moans upright ihumb rising above fist hand its characteristic ICONOGRAPHY', 'Śikhara (Mudra / Hasta): Literally denotes upright thumb rising above fist hand.', 12, 0.96, '{}');

-- -----------------------------------------------------------------------------
-- Table: ai_metadata_proposals [T_RAW_AI_PROPOSALS (Autonomous AI Metadata Proposals)] (9 rows)
-- -----------------------------------------------------------------------------
INSERT INTO ai_metadata_proposals (id, study_id, slide_id, slide_number, suggested_taxonomy_type, raw_suggested_term, mapped_term_id, confidence_score, evidence_snippet, review_status, curator_notes) VALUES ('pr1', 's_ganesa_001', 'sl_1', 1, 'divinity', 'Ganesa', 't_ganesha', 0.99, 'The iconography of Ganesa presents considerable variation in posture...', 'approved', 'Matched to canonical divinity Ganesha');
INSERT INTO ai_metadata_proposals (id, study_id, slide_id, slide_number, suggested_taxonomy_type, raw_suggested_term, mapped_term_id, confidence_score, evidence_snippet, review_status, curator_notes) VALUES ('pr2', 's_ganesa_001', 'sl_2', 2, 'iconographic_element', 'Mü$kavähana', 't_musika', 0.95, 'Mü$kavähana — mounted/seated upon the mü#ika', 'approved', 'OCR artifact mapped to Musika');
INSERT INTO ai_metadata_proposals (id, study_id, slide_id, slide_number, suggested_taxonomy_type, raw_suggested_term, mapped_term_id, confidence_score, evidence_snippet, review_status, curator_notes) VALUES ('pr3', 's_ganesa_001', 'sl_2', 2, 'iconographic_element', 'TriSuQ4a GaQapati', 't_trishunda', 0.98, 'TriSuQ4a GaQapati, Pune— three-trunked form', 'approved', 'OCR artifact mapped to Trishunda');
INSERT INTO ai_metadata_proposals (id, study_id, slide_id, slide_number, suggested_taxonomy_type, raw_suggested_term, mapped_term_id, confidence_score, evidence_snippet, review_status, curator_notes) VALUES ('pr4', 's_ganesa_001', 'sl_4', 4, 'iconographic_element', 'lalitäsana', 't_lalitasana', 0.99, 'or lalitäsana (posture of royal ease)', 'approved', 'Direct match to Lalitasana');
INSERT INTO ai_metadata_proposals (id, study_id, slide_id, slide_number, suggested_taxonomy_type, raw_suggested_term, mapped_term_id, confidence_score, evidence_snippet, review_status, curator_notes) VALUES ('pr_bd293cf8', 's_ganesa_001', 'sl_8b18a50ad6b8', 5, 'iconographic element', 'Lalitasana', 't_lalitasana', 0.95, '...(easy posture), lalitāsana (posture of royal ease), or ardhaparyaṅkāsana (with one leg —...', 'approved', 'Approved by curator in Visual Ingestion Studio');
INSERT INTO ai_metadata_proposals (id, study_id, slide_id, slide_number, suggested_taxonomy_type, raw_suggested_term, mapped_term_id, confidence_score, evidence_snippet, review_status, curator_notes) VALUES ('pr_17ab751e', 's_ganesa_001', 'sl_8b18a50ad6b8', 5, 'iconographic element', 'Asina', 't_asina', 0.95, '...ICONOGRAPHY POSTURAL VARIATIONS ĀSĪNA I SITTING In the āsīna form, Ganesa is...', 'approved', 'Approved by curator in Visual Ingestion Studio');
INSERT INTO ai_metadata_proposals (id, study_id, slide_id, slide_number, suggested_taxonomy_type, raw_suggested_term, mapped_term_id, confidence_score, evidence_snippet, review_status, curator_notes) VALUES ('pr_cd33b77b', 's_ganesa_001', 'sl_8b18a50ad6b8', 5, 'divinity', 'Ganesha', 't_ganesha', 0.95, '...IONS ĀSĪNA I SITTING In the āsīna form, Ganesa is represented seated in a stable and c...', 'approved', 'Approved by curator in Visual Ingestion Studio');
INSERT INTO ai_metadata_proposals (id, study_id, slide_id, slide_number, suggested_taxonomy_type, raw_suggested_term, mapped_term_id, confidence_score, evidence_snippet, review_status, curator_notes) VALUES ('pr_483712fc', 's_ganesa_001', 'sl_cc51fdf0d4d3', 5, 'divinity', 'Siva', 't_siva', 0.98, '...th: Deities holding bow (Rama, Forms of Siva, Devis), expressiVe iconographic gestur...', 'approved', 'Approved by curator in Visual Ingestion Studio');
INSERT INTO ai_metadata_proposals (id, study_id, slide_id, slide_number, suggested_taxonomy_type, raw_suggested_term, mapped_term_id, confidence_score, evidence_snippet, review_status, curator_notes) VALUES ('pr_003a7c8a', 's_ganesa_001', 'sl_09b140bc6fdb', 6, 'mudra', 'Shikhara Mudra', 't_shikhara_mudra', 0.98, 'Sikhara literally means upright thumb rising above fist hand...', 'approved', 'Approved by curator in Visual Ingestion Studio');
